module.exports =[
    {key:"Employee Code",value:"Employee Code"},
    {key:"FullName",value:"Full Name"},
    {key:"LastName",value:"Last Name"},
    {key:"MidName",value:"Middle Name"},
    {key:"FirstName",value:"First Name"},
    {key:"PhoneNumber",value:"Phone Number"},
    {key:"Technique",value:"Technique"},
    {key:"Position",value:"Position"},
    {key:"Gender",value:"Gender"},
    {key:"Signature",value:"Signature"},
    {key:"DateOfBirth",value:"Date Of Birth"},
    {key:"Retire",value:"Retire"},
    {key:"PlaceOfBirth",value:"Place Of Birth"},
    {key:"Domicile",value:"Domicile"},
    {key:"City",value:"City"},
    {key:"District",value:"District"},
    {key:"Ward",value:"Ward"},
    {key:"PermanentResidence",value:"Permanent Residence"},
    {key:"CurentAddress",value:"Curent Address"},
    {key:"ProvinceCity",value:"Province/City"},
    {key:"IdCard",value:"ID Card"},
    {key:"Passport",value:"Passport"},
    {key:"DateRange",value:"Date Range"},
    {key:"PlaceOfIssue",value:"Place Of Issue"},
    {key:"Residence",value:"Residence"},
    {key:"Nationnality",value:"Nationnality"},
    {key:"Nation",value:"Nation"},
    {key:"Religion",value:"Religion"},
    {key:"PhoneNumber",value:"Phone Number"},
    {key:"Email",value:"Email"},
    {key:"LaborContract",value:"Labor Contract"},
    {key:"Object",value:"Object"},
    {key:"DepartmentName",value:"Department Name"},
    {key:"DepartmentCode",value:"Department Code"},
    {key:"JobTitle",value:"Job Title"},
    {key:"JobTitleCode",value:"Job Title Code"},
    {key:"Diploma",value:"Diploma"},
    {key:"Timesheet",value:"Time sheet"},
    {key:"PaidLeave",value:"Paid Leave"},
    {key:"AnnualLeave",value:"Annual Leave"},
    {key:"CompassionateLeave",value:"Compassionate Leave"},
    {key:"PaternityLeave",value:"Paternity Leave"},
    {key:"MaternityLeave",value:"Maternity Leave"},
    {key:"SickLeave",value:"Sick Leave"},
    {key:"UnpaidLeave",value:"Unpaid Leave"},
    {key:"Payscale",value:"Payscale"},
    {key:"AverageSalary",value:"Average Salary"},
     {key:"TrainingSystem",value:"Training System"},
    {key:"TrainingSchool",value:"Training School"},
    {key:"GraduationYear",value:"Graduation Year"},
    {key:"Education",value:"Education"},
    {key:"AcademicLevel",value:"Academic Level"},
    {key:"NewPerson",value:"NewPerson"},
    {key:"NotSelect",value:"NotSelect"},
    {key:"ChooseDepartment",value:"ChooseDepartment"},
    {key:"Nonekey",value:"nonekey"},
    {key:"InformationTechnology",value:"Information Technology"},
    {key:"ForeignLanguage",value:"Foreign Language"},
    {key:"New",value:"New"},
    {key:"Update",value:"Update"},
    {key:"Delete",value:"Delete"},
    {key:"Specialized",value:"Specialized"},
    {key:"IT",value:"IT"},
    {key:"DegreeEnglish",value:"Degree English"},
    {key:"TypeLaborContract",value:"Labor Contract Type"},
    {key:"Living",value:"Living"},
    {key:"Domicile",value:"Domicile"},
    {key:"PlaceOfBirth",value:"Place of birth"},
    {key:"PermanentAddress",value:"Permanent Address"},
    {key:"Address",value:"Address"},
    {key:"Nationality",value:"Nationality"},
    {key:"TypeOfResidence",value:"Type Of Residence"},
    {key:"Degree",value:"Degree"},
    {key:"StateManagement",value:"State Management"},
    {key:"PoliticalTheory",value:"Political Theory"},
    {key:"EnglishDegree",value:"English Degree"},
    {key:"GeneralInfo",value:"General Information"},
    {key:"MissionInfo",value:"Mission Information"},
    {key:"EmployeeList",value:"Employee List"},
    {key:"BackgroundInformation",value:"Background information"},
    {key:"FamilyInformation",value:"Family information"},
    {key:"TrainingHistory",value:"Training history"},
    {key:"PracticingCertificate",value:"Practicing certificate"},
    {key:"PersonalAchievements",value:"Personal achievements"},
    {key:"InformationForLeave",value:"Information for leave"},
    {key:"ForeignWork",value:"Foreign work"},
    {key:"Father",value:"Father"},
    {key:"Mother",value:"Mother"},
    {key:"Yokefellow",value:"Yokefellow"},
    {key:"Brother",value:"Brother"},
    {key:"YoungerBrother",value:"Younger Brother"},
    {key:"Sister",value:"Sister"},
    {key:"YoungerSister",value:"YoungerSister"},
    {key:"Son",value:"Son"},
    {key:"Daughter",value:"Daughter"},
    {key:"Folk",value:"Folk"},
    {key:"Job",value:"Job"},
    {key:"BornYear",value:"Born year"},
    {key:"Relationship",value:"Relationship"},
    {key:"ListOfRelatives",value:"List of relatives"}
];