module.exports =[
    {key:"Employee Code",value:"Mã nhân viên"},
    {key:"FullName",value:"Họ và tên"},
    {key:"LastName",value:"Họ"},
    {key:"MidName",value:"Tên đệm"},
    {key:"FirstName",value:"Tên"},
    {key:"PhoneNumber",value:"Số điện thoại"},
    {key:"Technique",value:"Chuyên môn"},
    {key:"Position",value:"Chức vụ"},
    {key:"Gender",value:"Giới tính"},
    {key:"Signature",value:"Chữ ký"},
    {key:"DateOfBirth",value:"Ngày sinh"},
    {key:"Retire",value:"Hưu trí"},
    {key:"PlaceOfBirth",value:"Nơi sinh"},
    {key:"Domicile",value:"Nguyên quán"},
    {key:"City",value:"Tĩnh/Thành phố"},
    {key:"District",value:"Quận/Huyện"},
    {key:"Ward",value:"Phường/Xã"},
    {key:"PermanentResidence",value:"Hộ khẩu thường trú"},
    {key:"CurentAddress",value:"Nơi ở hiện tại"},
    {key:"ProvinceCity",value:"Tĩnh/Thành phố"},
    {key:"IdCard",value:"Số CMND"},
    {key:"Passport",value:"Hộ chiếu"},
    {key:"DateRange",value:"Ngày cấp"},
    {key:"PlaceOfIssue",value:"Nơi cấp"},
    {key:"Residence",value:"Loại hình cư trú"},
    {key:"Nationnality",value:"Quốc tịch"},
    {key:"Nation",value:"Dân tộc"},
    {key:"Religion",value:"Tôn giáo"},
    {key:"PhoneNumber",value:"Điện thoại"},
    {key:"Email",value:"Email"},
    {key:"Object",value:"Đối tượng"},
    {key:"DepartmentName",value:"Tên Khoa/Phòng"},
    {key:"DepartmentCode",value:"Mã Khoa/Phòng"},
    {key:"JobTitle",value:"Chức danh"},
    {key:"JobTitleCode",value:"Mã Chức danh"},
    {key:"Diploma",value:"Bằng cấp"},
    {key:"Timesheet",value:"Bảng chấm công"},
    {key:"PaidLeave",value:"Nghỉ phép thường niên"},
    {key:"AnnualLeave",value:"Nghỉ phép năm"},
    {key:"CompassionateLeave",value:"Nghỉ tang"},
    {key:"PaternityLeave",value:"Nghỉ vợ sinh con"},
    {key:"MaternityLeave",value:"Nghỉ thai sản"},
    {key:"SickLeave",value:"Nghỉ ốm"},
    {key:"UnpaidLeave",value:"Nghỉ phép không lương"},
    {key:"Payscale",value:"Bậc lương"},
    {key:"AverageSalary",value:"Lương cơ bản"},
    {key:"TrainingSystem",value:"Hệ đào tạo"},
    {key:"TrainingSchool",value:"Trường đào tạo"},
    {key:"GraduationYear",value:"Năm tốt nghiệp"},
    {key:"Education",value:"Học vấn"},
    {key:"AcademicLevel",value:"Trình độ học vấn"},
    {key:"InformationTechnology",value:"Tin học"},
    {key:"NewPerson",value:"Tạo mới nhân sự"},
    {key:"NotSelect",value:"Chưa chọn"},
    {key:"ChooseDepartment",value:"Chọn Phòng Ban"},
    {key:"Nonekey",value:"Chưa chọn từ khóa"},
    {key:"ForeignLanguage",value:"Ngoại ngữ"},
    {key:"New",value:"Thêm mới"},
    {key:"Update",value:"Cập nhật thông tin"},
    {key:"Delete",value:"Xoá"},
    {key:"LaborContract",value:"Hợp đồng lao động"},
    {key:"Specialized",value:"Chuyên ngành"},
    {key:"IT",value:"IT"},
    {key:"DegreeEnglish",value:"Trình độ Tiếng Anh"},
    {key:"TypeLaborContract",value:"Loại hợp đồng lao động"},
    {key:"Domicile",value:"Nguyên quán"},
    {key:"PlaceOfBirth",value:"Nơi sinh"},
    {key:"Living",value:"Nơi ở"},
    {key:"PermanentAddress",value:"Địa chỉ thường trú"},
    {key:"Address",value:"Địa chỉ"},
    {key:"Nationality",value:"Quốc tịch"},
    {key:"TypeOfResidence",value:"Loại hình cư trú"},
    {key:"Degree",value:"Trình độ"},
    {key:"StateManagement",value:"Quản lý nhà nước"},
    {key:"PoliticalTheory",value:"Lý luận chính trị"},
    {key:"EnglishDegree",value:"Trình độ tiếng Anh"},
    {key:"GeneralInfo",value:"Thông tin chung"},
    {key:"MissionInfo",value:"Thông tin công tác"},
    {key:"EmployeeList",value:"Danh sách nhân sự"},
    {key:"BackgroundInformation",value:"Thông tin lai lịch"},
    {key:"FamilyInformation",value:"Thông tin gia đình"},
    {key:"TrainingHistory",value:"Quá trình đào tạo"},
    {key:"PracticingCertificate",value:"Chứng chỉ hành nghề"},
    {key:"PersonalAchievements",value:"Thành tích cá nhân"},
    {key:"InformationForLeave",value:"Thông tin nghỉ phép"},
    {key:"ForeignWork",value:"Công tác nước ngoài"},
    {key:"Father",value:"Cha"},
    {key:"Mother",value:"Mẹ"},
    {key:"Yokefellow",value:"Vợ chồng"},
    {key:"Brother",value:"Anh trai"},
    {key:"YoungerBrother",value:"Em trai"},
    {key:"Sister",value:"Chị gái"},
    {key:"YoungerSister",value:"Em gái"},
    {key:"Son",value:"Con trai"},
    {key:"Daughter",value:"Con gái"},
    {key:"Folk",value:"Dân tộc"},
    {key:"Job",value:"Nghề nghiệp"},
    {key:"BornYear",value:"Năm sinh"},
    {key:"Relationship",value:"Mối quan hệ"},
    {key:"ListOfRelatives",value:"Danh sách người thân"}
];