module.exports = [
    // General / Navigation
    { key: "Menu", value: "Menu" },
    { key: "MyTasks", value: "My Tasks" },
    { key: "AssignedToMe", value: "Assigned to me" },
    { key: "TodayAndOverdue", value: "Today & Overdue" },
    { key: "Spaces", value: "Spaces" },
    { key: "NewSpace", value: "New Space" },
    { key: "WelcomeBack", value: "Welcome back" },
    { key: "Themes", value: "Themes" },
    { key: "ChooseYourTheme", value: "Choose Your Theme" },
    { key: "ThemeDesc", value: "Customize your interface appearance" },
    { key: "LightMode", value: "Light Mode" },
    { key: "LightModeDesc", value: "Perfect for bright environments and detailed work" },
    { key: "DarkMode", value: "Dark Mode" },
    { key: "DarkModeDesc", value: "Easy on the eyes, perfect for low light conditions" },
    { key: "SaveTheme", value: "Save Theme" },
    { key: "NoChanges", value: "No Changes" },
    { key: "LightModePreview", value: "Light Mode Preview" },
    { key: "DarkModePreview", value: "Dark Mode Preview" },
    { key: "Dashboard", value: "Dashboard" },
    { key: "Calendar", value: "Calendar" },
    { key: "Messages", value: "Messages" },

    // Dashboard
    { key: "ProjectsIntro", value: "Here's what's happening with your projects today" },
    { key: "TotalProjects", value: "Total Projects" },
    { key: "PendingTasks", value: "Pending Tasks" },
    { key: "Completed", value: "Completed" },
    { key: "NoActiveProjects", value: "No active projects" },
    { key: "GetStartedProject", value: "Get started by creating a new project or inviting your team members to collaborate." },
    { key: "CreateNewProject", value: "Create New Project" },

    // Settings
    { key: "SettingsDesc", value: "Manage your preferences and account settings" },
    { key: "Appearance", value: "Appearance" },
    { key: "AppearanceDesc", value: "Customize how the app looks and feels" },
    { key: "Theme", value: "Theme" },
    { key: "Notifications", value: "Notifications" },
    { key: "NotificationsDesc", value: "Choose what notifications you want to receive" },
    { key: "EmailNotifications", value: "Email notifications" },
    { key: "PushNotifications", value: "Push notifications" },
    { key: "TaskReminders", value: "Task reminders" },
    { key: "ProjectUpdates", value: "Project updates" },
    { key: "SystemAlerts", value: "System alerts" },
    { key: "MarketingEmails", value: "Marketing emails" },
    { key: "PrivacySecurity", value: "Privacy & Security" },
    { key: "PrivacySecurityDesc", value: "Control your privacy and security settings" },
    { key: "ProfileVisibility", value: "Profile visibility" },
    { key: "FriendsOnly", value: "Friends only" },
    { key: "ShowOnlineStatus", value: "Show online status" },
    { key: "AllowDirectMessages", value: "Allow direct messages" },
    { key: "DataSharing", value: "Data sharing with partners" },
    { key: "AnalyticsTracking", value: "Analytics tracking" },
    { key: "Preferences", value: "Preferences" },
    { key: "PreferencesDesc", value: "Customize your app experience" },
    { key: "AutoSaveDrafts", value: "Auto-save drafts" },
    { key: "ConfirmBeforeDelete", value: "Confirm before deleting" },
    { key: "ShowTips", value: "Show tips and hints" },
    { key: "CompactMode", value: "Compact mode" },
    { key: "SoundEffects", value: "Sound effects" },
    { key: "Animations", value: "Animations" },
    { key: "AccountInformation", value: "Account Information" },
    { key: "AccountInfoDesc", value: "Your account details and status" },
    { key: "AccountID", value: "Account ID" },
    { key: "Username", value: "Username" },
    { key: "Email", value: "Email" },
    { key: "Phone", value: "Phone" },
    { key: "Address", value: "Address" },
    { key: "Bio", value: "Bio" },
    { key: "MemberSince", value: "Member since" },
    { key: "LastLogin", value: "Last login" },
    { key: "Active", value: "Active" },
    { key: "SaveSettings", value: "Save Settings" },
    { key: "Saving", value: "Saving..." },
    { key: "Cancel", value: "Cancel" },
    { key: "Overview", value: "Overview" },
    { key: "EditProfile", value: "Edit Profile" },
    { key: "ChangePassword", value: "Change Password" },
    { key: "AccountSettings", value: "Account Settings" },
    { key: "ProfileOverview", value: "Profile Overview" },
    { key: "FullName", value: "Full Name" },
    { key: "SaveChanges", value: "Save Changes" },
    { key: "TellUsAboutYourself", value: "Tell us about yourself..." },
    { key: "CurrentPassword", value: "Current Password" },
    { key: "EnterCurrentPassword", value: "Enter current password" },
    { key: "NewPassword", value: "New Password" },
    { key: "EnterNewPassword", value: "Enter new password" },
    { key: "ConfirmNewPassword", value: "Confirm New Password" },
    { key: "AccountStatus", value: "Account Status" },
    { key: "TwoFactorAuth", value: "Two-Factor Authentication" },
    { key: "TwoFactorDesc", value: "Add an extra layer of security to your account" },
    { key: "Setup2FA", value: "Setup 2FA" },
    { key: "DangerZone", value: "Danger Zone" },
    { key: "IrreversibleAction", value: "Irreversible and destructive actions" },
    { key: "DeleteAccount", value: "Delete Account" },
    { key: "Edit", value: "Edit" },
    { key: "Changing", value: "Changing..." },

    // Project Detail
    { key: "List", value: "List" },
    { key: "Board", value: "Board" },
    { key: "Gantt", value: "Gantt" },
    { key: "Table", value: "Table" },
    { key: "Space", value: "Space" },
    { key: "Open", value: "Open" },
    { key: "Loading", value: "Loading..." },
    { key: "NoProjects", value: "No projects" },
    { key: "Agents", value: "Agents" },
    { key: "Automate", value: "Automate" },
    { key: "Ask", value: "Ask" },
    { key: "Share", value: "Share" },
    { key: "View", value: "View" },
    { key: "WelcomeToProject", value: "Welcome to" },
    { key: "ContentForView", value: "Content for {{view}} view goes here." },
    { key: "GroupNone", value: "Group: None" },
    { key: "Subtasks", value: "Subtasks" },
    { key: "Columns", value: "Columns" },
    { key: "SaveView", value: "Save view" },
    { key: "Filter", value: "Filter" },
    { key: "Closed", value: "Closed" },
    { key: "Assignee", value: "Assignee" },
    { key: "Search", value: "Search" },
    { key: "Customize", value: "Customize" },
    { key: "AddTask", value: "Add Task" },
    { key: "Name", value: "Name" },
    { key: "DueDate", value: "Due date" },
    { key: "Priority", value: "Priority" },
    { key: "Status", value: "Status" },
    { key: "Comments", value: "Comments" },
    { key: "AddTaskPlaceholder", value: "Add Task" },
    { key: "ProjectNotFound", value: "Project not found" },
    { key: "Projects", value: "Projects" },

    // Space Detail
    { key: "SpaceNotFound", value: "Space not found" },
    { key: "AddChannel", value: "Add Channel" },
    { key: "Filters", value: "Filters" },
    { key: "Refreshed", value: "Refreshed" },
    { key: "minsAgo", value: "mins ago" },
    { key: "AutoRefreshOn", value: "Auto refresh: On" },
    { key: "AddCard", value: "Add card" },
    { key: "InSpace", value: "in" },
    { key: "NoRecentProjects", value: "No recent projects" },
    { key: "NoDocsHere", value: "There are no Docs in this location yet." },
    { key: "AddDoc", value: "Add a Doc" },

    // Sidebar
    { key: "Rename", value: "Rename" },
    { key: "CopyLink", value: "Copy link" },
    { key: "CreateNew", value: "Create new" },
    { key: "Doc", value: "Doc" },
    { key: "Folder", value: "Folder" },
    { key: "ColorAndIcon", value: "Color & Icon" },
    { key: "Icon", value: "Icon" },
    { key: "SearchIcons", value: "Search icons..." },
    { key: "HideProject", value: "Hide Project" },
    { key: "HideSpace", value: "Hide Space" },
    { key: "HideProjectDesc", value: "You'll retain access to this Project, but it won't show in your sidebar" },
    { key: "HideSpaceDesc", value: "You'll retain access to this Space, but it won't show in your sidebar" },
    { key: "CreateSpace", value: "Create Space" },

    // Create Task Modal
    { key: "PriorityUrgent", value: "Urgent" },
    { key: "PriorityHigh", value: "High" },
    { key: "PriorityNormal", value: "Normal" },
    { key: "PriorityLow", value: "Low" },
    { key: "SelectPriority", value: "Select Priority" },
    { key: "SetPriority", value: "Set Priority" },
    { key: "SetDueDate", value: "Set Due Date" },
    { key: "Today", value: "Today" },
    { key: "Tomorrow", value: "Tomorrow" },
    { key: "NextWeek", value: "Next Week" },
    { key: "NoDate", value: "No Date" },
    { key: "CustomDate", value: "Custom Date" },
    { key: "SelectAssignee", value: "Select Assignee" },
    { key: "ProTip", value: "Pro tip:" },
    { key: "QuickCreate", value: "to quick create" },
    { key: "ClickToUpload", value: "Click to upload or drag and drop" },
    { key: "ClickToUploadShort", value: "Click to upload" },
    { key: "ClickToUploadShort", value: "Click to upload" },
    { key: "FileTypes", value: "SVG, PNG, JPG or GIF (max. 10MB)" },
    { key: "TaskTitlePlaceholder", value: "What needs to be done?" },
    { key: "TaskDescriptionPlaceholder", value: "Add a detailed description... (Type '/' for commands)" },
    { key: "StartDate", value: "Start date" },
    { key: "Later", value: "Later" },
    { key: "ThisWeekend", value: "This weekend" },
    { key: "NextWeekend", value: "Next weekend" },
    { key: "TwoWeeks", value: "2 weeks" },
    { key: "FourWeeks", value: "4 weeks" },
    { key: "SetRecurring", value: "Set Recurring" },
    { key: "SelectDate", value: "Select date" },
    { key: "SelectStatus", value: "Select Status" },
    { key: "TaskCreatedSuccessfully", value: "Task created successfully!" },
    { key: "TaskCreationFailed", value: "Failed to create task. Please try again." },
    { key: "SpaceCreatedSuccessfully", value: "Space created successfully!" },
    { key: "SpaceCreationFailed", value: "Failed to create space. Please try again." },
    { key: "Done", value: "Done" }
];
