module.exports = [
    // General / Navigation
    { key: "Menu", value: "Menu" },
    { key: "MyTasks", value: "Công việc của tôi" },
    { key: "AssignedToMe", value: "Được giao cho tôi" },
    { key: "TodayAndOverdue", value: "Hôm nay & Quá hạn" },
    { key: "Spaces", value: "Không gian" },
    { key: "NewSpace", value: "Tạo mới không gian" },
    { key: "WelcomeBack", value: "Chào mừng trở lại" },
    { key: "Themes", value: "Chủ đề" },
    { key: "ChooseYourTheme", value: "Chọn giao diện" },
    { key: "ThemeDesc", value: "Tùy chỉnh giao diện ứng dụng của bạn" },
    { key: "LightMode", value: "Chế độ Sáng" },
    { key: "LightModeDesc", value: "Phù hợp cho môi trường sáng và làm việc chi tiết" },
    { key: "DarkMode", value: "Chế độ Tối" },
    { key: "DarkModeDesc", value: "Dễ chịu cho mắt, phù hợp điều kiện thiếu sáng" },
    { key: "SaveTheme", value: "Lưu giao diện" },
    { key: "NoChanges", value: "Không có thay đổi" },
    { key: "LightModePreview", value: "Xem trước Sáng" },
    { key: "DarkModePreview", value: "Xem trước Tối" },
    { key: "Dashboard", value: "Bảng điều khiển" },
    { key: "Calendar", value: "Lịch" },
    { key: "Messages", value: "Tin nhắn" },

    // Dashboard
    { key: "ProjectsIntro", value: "Đây là tình hình các dự án của bạn hôm nay" },
    { key: "TotalProjects", value: "Tổng dự án" },
    { key: "PendingTasks", value: "Công việc chờ" },
    { key: "Completed", value: "Đã hoàn thành" },
    { key: "NoActiveProjects", value: "Không có dự án hoạt động" },
    { key: "GetStartedProject", value: "Bắt đầu bằng cách tạo dự án mới hoặc mời thành viên vào nhóm." },
    { key: "CreateNewProject", value: "Tạo dự án mới" },

    // Settings
    { key: "SettingsDesc", value: "Quản lý tùy chọn và cài đặt tài khoản" },
    { key: "Appearance", value: "Giao diện" },
    { key: "AppearanceDesc", value: "Tùy chỉnh giao diện ứng dụng" },
    { key: "Theme", value: "Chủ đề" },
    { key: "Notifications", value: "Thông báo" },
    { key: "NotificationsDesc", value: "Chọn loại thông báo bạn muốn nhận" },
    { key: "EmailNotifications", value: "Thông báo qua Email" },
    { key: "PushNotifications", value: "Thông báo đẩy" },
    { key: "TaskReminders", value: "Nhắc nhở công việc" },
    { key: "ProjectUpdates", value: "Cập nhật dự án" },
    { key: "SystemAlerts", value: "Cảnh báo hệ thống" },
    { key: "MarketingEmails", value: "Email quảng cáo" },
    { key: "PrivacySecurity", value: "Riêng tư & Bảo mật" },
    { key: "PrivacySecurityDesc", value: "Kiểm soát cài đặt riêng tư và bảo mật" },
    { key: "ProfileVisibility", value: "Hiển thị hồ sơ" },
    { key: "FriendsOnly", value: "Chỉ bạn bè" },
    { key: "ShowOnlineStatus", value: "Hiển thị trạng thái online" },
    { key: "AllowDirectMessages", value: "Cho phép tin nhắn trực tiếp" },
    { key: "DataSharing", value: "Chia sẻ dữ liệu với đối tác" },
    { key: "AnalyticsTracking", value: "Theo dõi phân tích" },
    { key: "Preferences", value: "Tùy chọn" },
    { key: "PreferencesDesc", value: "Tùy chỉnh trải nghiệm ứng dụng" },
    { key: "AutoSaveDrafts", value: "Tự động lưu nháp" },
    { key: "ConfirmBeforeDelete", value: "Xác nhận trước khi xóa" },
    { key: "ShowTips", value: "Hiển thị mẹo và gợi ý" },
    { key: "CompactMode", value: "Chế độ thu gọn" },
    { key: "SoundEffects", value: "Hiệu ứng âm thanh" },
    { key: "Animations", value: "Hiệu ứng chuyển động" },
    { key: "AccountInformation", value: "Thông tin tài khoản" },
    { key: "AccountInfoDesc", value: "Chi tiết và trạng thái tài khoản của bạn" },
    { key: "AccountID", value: "ID Tài khoản" },
    { key: "Username", value: "Tên đăng nhập" },
    { key: "Email", value: "Email" },
    { key: "Phone", value: "Số điện thoại" },
    { key: "Address", value: "Địa chỉ" },
    { key: "Bio", value: "Giới thiệu" },
    { key: "MemberSince", value: "Thành viên từ" },
    { key: "LastLogin", value: "Đăng nhập lần cuối" },
    { key: "Active", value: "Hoạt động" },
    { key: "SaveSettings", value: "Lưu cài đặt" },
    { key: "Saving", value: "Đang lưu..." },
    { key: "Cancel", value: "Hủy" },
    { key: "Overview", value: "Tổng quan" },
    { key: "EditProfile", value: "Chỉnh sửa hồ sơ" },
    { key: "ChangePassword", value: "Đổi mật khẩu" },
    { key: "AccountSettings", value: "Cài đặt tài khoản" },
    { key: "ProfileOverview", value: "Tổng quan hồ sơ" },
    { key: "FullName", value: "Họ và tên" },
    { key: "SaveChanges", value: "Lưu thay đổi" },
    { key: "TellUsAboutYourself", value: "Hãy giới thiệu về bản thân bạn..." },
    { key: "CurrentPassword", value: "Mật khẩu hiện tại" },
    { key: "EnterCurrentPassword", value: "Nhập mật khẩu hiện tại" },
    { key: "NewPassword", value: "Mật khẩu mới" },
    { key: "EnterNewPassword", value: "Nhập mật khẩu mới" },
    { key: "ConfirmNewPassword", value: "Xác nhận mật khẩu mới" },
    { key: "AccountStatus", value: "Trạng thái tài khoản" },
    { key: "TwoFactorAuth", value: "Xác thực hai yếu tố (2FA)" },
    { key: "TwoFactorDesc", value: "Thêm một lớp bảo mật cho tài khoản của bạn" },
    { key: "Setup2FA", value: "Thiết lập 2FA" },
    { key: "DangerZone", value: "Khu vực nguy hiểm" },
    { key: "IrreversibleAction", value: "Hành động không thể hoàn tác" },
    { key: "DeleteAccount", value: "Xóa tài khoản" },
    { key: "Edit", value: "Chỉnh sửa" },
    { key: "Changing", value: "Đang đổi..." },

    // Project Detail
    { key: "List", value: "Danh sách" },
    { key: "Board", value: "Bảng" },
    { key: "Gantt", value: "Gantt" },
    { key: "Table", value: "Bảng tính" },
    { key: "Space", value: "Không gian" },
    { key: "Open", value: "Mở" },
    { key: "Loading", value: "Đang tải..." },
    { key: "NoProjects", value: "Không có dự án" },
    { key: "Agents", value: "Agents" },
    { key: "Automate", value: "Tự động hóa" },
    { key: "Ask", value: "Hỏi" },
    { key: "Share", value: "Chia sẻ" },
    { key: "View", value: "Xem" },
    { key: "WelcomeToProject", value: "Chào mừng đến với" },
    { key: "ContentForView", value: "Nội dung cho chế độ xem {{view}} hiển thị ở đây." },
    { key: "GroupNone", value: "Nhóm: Không" },
    { key: "Subtasks", value: "Công việc con" },
    { key: "Columns", value: "Cột" },
    { key: "SaveView", value: "Lưu chế độ xem" },
    { key: "Filter", value: "Bộ lọc" },
    { key: "Closed", value: "Đã đóng" },
    { key: "Assignee", value: "Người thực hiện" },
    { key: "Search", value: "Tìm kiếm" },
    { key: "Customize", value: "Tùy chỉnh" },
    { key: "AddTask", value: "Thêm công việc" },
    { key: "Name", value: "Tên" },
    { key: "DueDate", value: "Ngày hết hạn" },
    { key: "Priority", value: "Độ ưu tiên" },
    { key: "Status", value: "Trạng thái" },
    { key: "Comments", value: "Bình luận" },
    { key: "AddTaskPlaceholder", value: "Thêm công việc" },
    { key: "ProjectNotFound", value: "Không tìm thấy dự án" },
    { key: "Projects", value: "Dự án" },

    // Space Detail
    { key: "SpaceNotFound", value: "Không tìm thấy không gian" },
    { key: "AddChannel", value: "Thêm kênh" },
    { key: "Filters", value: "Bộ lọc" },
    { key: "Refreshed", value: "Đã làm mới" },
    { key: "minsAgo", value: "phút trước" },
    { key: "AutoRefreshOn", value: "Tự động làm mới: Bật" },
    { key: "AddCard", value: "Thêm thẻ" },
    { key: "InSpace", value: "trong" },
    { key: "NoRecentProjects", value: "Không có dự án gần đây" },
    { key: "NoDocsHere", value: "Chưa có tài liệu nào ở đây." },
    { key: "AddDoc", value: "Thêm tài liệu" },

    // Sidebar
    { key: "Rename", value: "Đổi tên" },
    { key: "CopyLink", value: "Sao chép liên kết" },
    { key: "CreateNew", value: "Tạo mới" },
    { key: "Doc", value: "Tài liệu" },
    { key: "Folder", value: "Thư mục" },
    { key: "ColorAndIcon", value: "Màu sắc & Biểu tượng" },
    { key: "Icon", value: "Biểu tượng" },
    { key: "SearchIcons", value: "Tìm kiếm biểu tượng..." },
    { key: "HideProject", value: "Ẩn dự án" },
    { key: "HideSpace", value: "Ẩn không gian" },
    { key: "HideProjectDesc", value: "Bạn vẫn có quyền truy cập dự án này, nhưng nó sẽ không hiện trên thanh bên" },
    { key: "HideSpaceDesc", value: "Bạn vẫn có quyền truy cập không gian này, nhưng nó sẽ không hiện trên thanh bên" },
    { key: "CreateSpace", value: "Tạo không gian" },

    // Create Task Modal
    { key: "PriorityUrgent", value: "Khẩn cấp" },
    { key: "PriorityHigh", value: "Cao" },
    { key: "PriorityNormal", value: "Bình thường" },
    { key: "PriorityLow", value: "Thấp" },
    { key: "SelectPriority", value: "Chọn độ ưu tiên" },
    { key: "SetPriority", value: "Đặt độ ưu tiên" },
    { key: "SetDueDate", value: "Đặt ngày hết hạn" },
    { key: "Today", value: "Hôm nay" },
    { key: "Tomorrow", value: "Ngày mai" },
    { key: "NextWeek", value: "Tuần tới" },
    { key: "NoDate", value: "Không có ngày" },
    { key: "CustomDate", value: "Ngày tùy chọn" },
    { key: "SelectAssignee", value: "Chọn người thực hiện" },
    { key: "ProTip", value: "Mẹo:" },
    { key: "QuickCreate", value: "để tạo nhanh" },
    { key: "ClickToUpload", value: "Nhấn để tải lên hoặc kéo thả" },
    { key: "ClickToUploadShort", value: "Nhấn để tải lên" },
    { key: "ClickToUploadShort", value: "Nhấn để tải lên" },
    { key: "FileTypes", value: "SVG, PNG, JPG hoặc GIF (tối đa 10MB)" },
    { key: "TaskTitlePlaceholder", value: "Cần làm những gì?" },
    { key: "TaskDescriptionPlaceholder", value: "Thêm mô tả chi tiết... (Gõ '/' cho các lệnh)" },
    { key: "StartDate", value: "Ngày bắt đầu" },
    { key: "Later", value: "Sau đó" },
    { key: "ThisWeekend", value: "Cuối tuần này" },
    { key: "NextWeekend", value: "Cuối tuần sau" },
    { key: "TwoWeeks", value: "2 tuần" },
    { key: "FourWeeks", value: "4 tuần" },
    { key: "SetRecurring", value: "Lặp lại" },
    { key: "SelectDate", value: "Chọn ngày" },
    { key: "SelectStatus", value: "Chọn trạng thái" },
    { key: "TaskCreatedSuccessfully", value: "Tạo công việc thành công!" },
    { key: "TaskCreationFailed", value: "Tạo công việc thất bại. Vui lòng thử lại." },
    { key: "SpaceCreatedSuccessfully", value: "Tạo không gian thành công!" },
    { key: "SpaceCreationFailed", value: "Tạo không gian thất bại. Vui lòng thử lại." },
    { key: "Done", value: "Xong" }
];
