module.exports=[
    {key:"UpdateStudyPlan",value:"Update Study Plan"},
    {key:"UploadHistory",value:"Upload History"},
    {key:"DoYouWantDeleteStudyPlan",value: "Do you want delete study plan: {{title}}?"},
    {key:"UpdateExamSchedule",value:"Update Exam Schedule"},
    {key:"DoYouWantDeleteExamSchedule",value: "Do you want delete exam schedule: {{title}}?"},
    {key:"answer",value: "Answer"},
    {key:"open",value: "Opend"},
    {key:"answered",value: "Answered"},
    {key:"resolve",value: "Resolve"},
    {key:"reject",value: "Reject"},
    {key:"waiting",value: "Waiting"},
    {key:"question",value: "Question"},
    {key:"DateUpload",value: "Date Upload"},
    {key:"InputNameFileOrNameCreator",value: "Input name file or name creator"},
    {key:"EventQuantity",value: "Event Quantity"},
    {key:"EventPoint",value: "Event Point"},
    {key:"EventTime",value: "Event Time"},
    {key:"EventRegister",value: "Event Register"},
    {key:"CreatetrainingPointActivity",value:"Create training point activity"},
    {key:"RegistrationEndDate",value:"Registration End Date"},
    {key:"RegistrationStartDate",value:"Registration Start Date"},
    {key:"TrainingPoint",value:"Training Point"},
    {key:"Point",value:"Point"},
    {key:"Store",value:"Store"},
    {key:"Event",value:"Event"},
    {key:"EventList",value:"Event List"},
    {key:"UpdateTrainingPointActivity",value:"Update Training Point Activity"},
    {key:"SearchEvent",value:"Search Event"},
    {key:"CannotDeleteAnItemHaveRegisteredMember",value:"Cannot delete an item have registered member"},
];
