module.exports=[
    {key:"UpdateStudyPlan",value:"Cập nhật lịch học"},
    {key:"UploadHistory",value:"Lịch sử tải file"},
    {key:"DoYouWantDeleteStudyPlan",value: "Bạn có muốn xoá lịch học: {{title}}?"},
    {key:"UpdateExamSchedule",value:"Cập nhật lịch thi"},
    {key:"DoYouWantDeleteExamSchedule",value: "Bạn có muốn xoá lịch thi:{{title}}?"},
    {key:"answer",value: "Câu trả lời"},
    {key:"open",value: "Đang mở đợi phản hồi"},
    {key:"answered",value: "Đã có câu trả lời"},
    {key:"resolve",value: "Câu hỏi đã được giải quyết"},
    {key:"reject",value: "Từ chối câu hỏi"},
    {key:"waiting",value: "Đang chờ để trả lời"},
    {key:"question",value: "Câu hỏi"},
    {key:"DateUpload",value: "Ngày Upload"},
    {key:"InputNameFileOrNameCreator",value: "Nhập tên tệp hoặc tên người tạo"},
    {key:"EventQuantity",value: "Số lượng"},
    {key:"EventPoint",value: "Điểm sự kiện"},
    {key:"EventTime",value: "Thời gian sự kiện"},
    {key:"EventRegister",value: "Thời gian đăng ký sự kiện"},
    {key:"CreatetrainingPointActivity",value:"Thêm sự kiện "},
    {key:"RegistrationEndDate",value:"Ngày kết thúc đăng ký"},
    {key:"RegistrationStartDate",value:"Ngày bắt đầu đăng ký"},  
    {key:"TrainingPoint",value:"Điểm rèn luyện"},
    {key:"Point",value:"Điểm"},
    {key:"Store",value:"Khởi tạo"},
    {key:"Event",value:"Sự kiện"},
    {key:"EventList",value:"Danh sách sự kiện"},
    {key:"UpdateTrainingPointActivity",value:"Cập nhật sự kiện"},
    {key:"SearchEvent",value:"Tìm kiếm sự kiện"},
    {key:"CannotDeleteAnItemHaveRegisteredMember",value:"Không thể xoá sự kiện đã có người đăng ký"},
];
