module.exports=[
    {key:"Me",value:"Me"},
    {key:"public",value:"public"},
    {key:"pending",value:"pending"},
    {key:"Events",value:"Events"},
    {key:"created",value:"created"},
    {key:"updated",value:"updated"},
    {key:"Project",value:"Project"},
    {key:"NewProject",value:"New Project"},
    {key:"WikiNew",value:"New Wiki"},
    {key:"WikiUpdate",value:"Update Wiki"},
    {key:"DBName",value:"Database Name"},
    {key:"Collection",value:"Collection"},
    {key:"Time",value:"Time"},
    {key:"WrittenBy",value:"Written By"},
    {key:"SaveBy",value:"Save by"},
    {key:"Name",value:"Name"},
    {key:"Display",value:"Display"},
    {key:"DoYouWantToDeleteFollowData",value:"Do you want to delete follow data"},
    {key:"Activate",value:"Activate"},
    {key:"Deactivate",value:"Deactivate"},
    {key:"Branch",value:"Branch"},
    {key:"Competence",value:"Competence"},
    {key:"NotSelectedYet",value:"Not selected yet"},
    {key:"Pick",value:"Pick"},
    {key:"AttachedFile",value:"Attached file"},
    {key:"UploadFile",value:"Upload file"},
    {key:"UploadFolder",value:"Upload folder"},
    {key:"DragTheFileHereToUpload",value:"Drag the file here to upload"},
    {key:"DragTheFolderHereToUpload",value:"Drag the folder here to upload"},
    {key:"TheFileWillAutomaticallyUploadWhenSelected",value:"The file will automatically upload when selected"},
    {key:"UploadImage",value:"Upload image"},
    {key:"DragTheImageHereToUpload",value:"Drag the image here to upload"},
    {key:"DetailsInformation",value:"DetailsInformation"},
    {key:"Approval",value:"Approval"},
    {key:"SignOther",value:"Sign other"},
    {key:"Reject",value:"Reject"},
    {key:"Approving",value:"Approving"},
    {key:"Rejecting",value:"Rejecting"},
    {key:"SuccessApproval",value:"Success Approving"},
    {key:"SuccessReject",value:"Success Reject"},
    {key:"SuccessReturn",value:"Success Return"},
    {key:"SuccessResubmit",value:"Success Resubmit"},
    {key:"SuccessSign",value:"Success Sign"},
    {key:"All",value:"All"},
    {key:"Spending",value:"Spending"},
    { key: "Pending", value: "Pending" },
    {key:"ApprovedByDepartmentLeader",value:"Approved by department leader"},
    {key:"Processing",value:"Processing"},
    {key:"PleaseCheckInformation",value:"Please check information"},
    {key:"DataIsNull",value:"Data is null"},
    {key:"ExistAccount",value:"Exist Account"},
    {key:"Register",value:"Register"},
    {key:"Workflow",value:"Workflow"},
    {key:"DocumentType",value:"Document type"},
    {key:"TypeName",value:"Type name"},
    {key:"TemplateFile",value:"Template File"},
    {key:"ApprovalType",value:"ApprovalType"},
    {key:"Signing",value:"Signing"},
    {key:"WorkflowForMe",value:"Workflow For Me"},
    {key:"FeaturePopular",value:"Feature Popular"},
    {key:"WorkflowPlay",value:"Process"},
    {key:"ApproverIsNull",value:"Approver Is Null"},
    {key:"Created",value:"Created"},
    {key:"Approved",value:"Approved"},
    {key:"Handled",value:"Handled"},
    {key:"Approver",value:"Approver"},
    { key: "Rejected", value: "Rejected" },
    {key:"Reject",value:"Reject"},
    { key: "Returned", value: "Returned" },
    {key:"Approve",value:"Duyệt"},
    {key:"SaveODB",value:"Saved the outgoing dispatch"},
    {key:"SaveBriefCase",value:"Saved the briefcase"},
    {key:"transformSign",value:"has transform the sign to"},
    {key:"NeedToHandle",value:"Need to handle"},
    {key:"FileSigning",value:"File signing"},
    {key:"RelatedFile",value:"Related file"},
    {key:"Note",value:"Note"},
    {key:"InputNote",value:"Input note"},
    {key:"YourLanguage",value:"Your language"},
    {key:"Task",value:"Task"},
    {key:"Assigned",value:"Assigned"},
    {key:"FromDate",value:"From date"},
    {key:"ToDate",value:"To date"},
    {key:"Grade",value:"Grade"},
    {key:"MainPerson",value:"Main Person"},
    {key:"Participant",value:"Participant"},
    {key:"Observer",value:"Observer"},
    {key:"NotStartedYet",value:"Not started yet"},
    {key:"Responsibility",value:"Responsibility"},
    {key:"StartDoing",value:"Start"},
    {key:"vi-VN", value:"Vietnamese"},
    {key:"Completed",value:"Completed"},
    {key:"Unfinished",value:"Unfinished"},
    {key:"Comment",value:"Comment"},
    {key:"PostAComment",value:"Post a comment"},
    {key:"SuccessUpdating",value:"Success Updating"},
    {key:"LeaveForm",value:"Leave form"},
    {key:"NumberOfDays",value:"Number of days"},
    {key:"Reason",value:"Reason"},
    {key:"days",value:"days"},
    {key:"DispatchArrived",value:"Dispatch arrived"},
    {key:"DispatchOutgoing",value:"Dispatch outgoing"},
    {key:"DispatchArrivedType",value:"Type name"},
    {key:"DispatchArrivedBook",value:"Dispatch arrived book"},
    {key:"EmergencyLevel",value:"Emergency level"},
    {key:"ReceiveMethod",value:"Receive method"},
    {key:"SendMethod",value:"Send method"},
    {key:"Excerpt",value:"Extract"},
    {key:"DispatchArrivedDate",value:"Delivery date"},
    {key:"Transfer date",value:"Transfer date"},
    {key:"OutgoingDispatchBookDate",value:"Outgoing dispatch book date"},
    {key:"SaveDispatchBook",value:"Save dispatch book"},
    {key:"ReleaseDate",value:"Release date"},
    {key:"DateMonthYearDocument",value:"Date month year document"},
    {key:"Author",value:"Author"},
    {key:"UnitOrRecipientDocument",value:"The unit or recipient of the document"},
    {key:"PlaceOfDispatchArrived",value:"Place of dispatch arrived"},
    {key:"TheSigner",value:"the Signer"},
    {key:"IsLegalDocument",value:"Is legal document"},
    {key:"IsTheAssignmentDocument",value:"Is the assignment document"},
    {key:"PeopleHandling",value:"People handling"},
    {key:"AtLeast",value:"At least {{title}}"},
    {key:"Number",value:"Number"},
    {key:"Handling",value:"Handling"},
    {key:"Forward",value:"Forwarded"},
    {key:"AddTaskForThis",value:"Add a task for this"},
    {key:"AddNotifyForThis",value:"Add a notify for this"},
    {key:"NotRequired",value:"not required"},
    {key:"InvalidInformation",value:"Invalid information"},
    {key:"HandlingAndForward",value:"Handling and forward"},
    {key:"to",value:"to"},
    {key:"Action",value:"Action"},
    {key:"Seen",value:"Seen"},
    {key:"NotSeen",value:"NotSeen"},
    {key:"Employee",value:"Employee"},
    {key:"Sent",value:"Sent"},
    {key:"Notice",value:"Notice"},
    {key:"Reportscanonlybesentfromto",value:"Reports can only be sent and be modified from {{from}} to {{to}}"},
    {key:"TotalNurse_Technicians",value:"Total Nurse/Technicians"},
    {key:"NurseReport",value:"Nurse Report"},
    {key:"MyJourneyTimeForm",value:"My journey time form"},
    {key:"ExceptTimeOnRoad",value:"Except time on road"},
    {key:"AddJourneyTimeForm",value:"Add journey time form"},
    {key:"CancelJourneyTimeForm",value:"Cancel journey time form"},
    {key:"Cancel",value:"Cancel"},
    {key:"AdministrativeNursing_Technicians",value:"Administrative nursing/technicians"},
    {key:"OutShiftNursing_Technicians",value:"Out shift nursing/technicians"},
    {key:"NursingOutHospital",value:"Nursing out hospital"},
    {key:"MorningShiftNursing",value:"Morning shift Nursing"},
    {key:"AfternoonShiftNursing",value:"Afternoon shift nursing"},
    {key:"NightShiftNursing",value:"Night shift nursing"},
    {key:"OverShiftNursing",value:"Over shift nursing"},
    {key:"LeaveShiftNursing",value:"Leave shift nursing"},
    {key:"NursingAtClinic",value:"Nursing at clinic"},
    {key:"LeaveNursing",value:"Nursing leave"},
    {key:"MaternityLeaveNursing",value:"Maternity leave nursing"},
    {key:"SickLeaveNursing",value:"Sick leave nursing"},
    {key:"NursingGoSchool",value:"Nursing go school"},
    {key:"ApprenticeNursing",value:"Apprentice nursing"},
    {key:"ProbationaryNursing",value:"Probationary nursing"},
    {key:"OtherCase",value:"Other case"},
    {key:"RealBed",value:"Real bed"},
    {key:"PatientNumber",value:"Patient number"},
    {key:"Level1Care",value:"Level 1 care"},
    {key:"FinalPhasePatient",value:"Final phase patient"},
    {key:"VentilatorBase",value:"Ventilator base"},
    {key:"ActiveVentilator",value:"Active ventilator"},
    {key:"MonitorBase",value:"Monitor base"},
    {key:"ActiveMonitor",value:"Active monitor"},
    {key:"ElectricSyringeBase",value:"Electric syringe base"},
    {key:"ActiveElectricSyringe",value:"Active electric syringe"},
    {key:"DropsCounterBase",value:"Drops counter base"},
    {key:"ActiveDropsCounter",value:"Active drops counter"},
    {key:"General",value:"General"},
    {key:"Module",value:"Module"},
    {key:"Report",value:"Report"},
    {key:"Statistic",value:"Statistic"},
    {key:"Date",value:"Date"},
    {key:"Sum",value:"Sum"},
    {key:"ThingsNeedToHandle",value:"Things need to handle"},
    {key:"NotReportYet",value:"Not report yet"},
    {key:"LoadMoreNotify",value:"Load more notify"},
    {key:"Password",value:"Password"},
    {key:"NewPassword",value:"New password"},
    {key:"RetypeNewPassword",value:"Retype new password"},
    {key:"UpdateSuccessed",value:"Update successed"},
    {key:"ChangePasswordSuccessed",value:"Change password successed"},
    {key:"TryToUseNewPassword",value:"Try to use new password"},
    {key:"MyProfile",value:"My profile"},
    {key:"BasicSalary",value:"Basic salary"},
    {key:"Salary",value:"Salary"},
    {key:"NumberOfHours",value:"Number of hours"},
    {key:"SalaryHours",value:"Salary hours"},
    {key:"Hours",value:"Hours"},
    {key:"Applicable for main person only",value:"Applicable for main person only"},
    {key:"NotCompleted",value:"Not completed"},
    {key:"OutDeadline",value:"Out deadline"},
    {key:"Done",value:"Done"},
    {key:"DoneDone",value:"Done"},
    {key:"WaitingForApproval",value:"Waiting For Approval"},
    {key:"Approve",value:"Approve"},
    {key:"Close",value:"Close"},
    {key:"CreatedChildTask",value:"Created child task"},
    {key:"ChildTask",value:"Child task"},
    {key:"ParentTask",value:"Parent task"},
    {key:"Staff",value:"Staff"},
    {key:"UpdatedInformation",value:"UpdatedInformation"},
    {key:"BirthDay",value:"Birthday"},
    {key:"DateOfBirth",value:"Date of birth"},
    {key:"SelfDeclaration",value:"Self declaration"},
    {key:"EmployeeCode",value:"Employee code"},
    {key:"DuplicateData",value:"Duplicate data"},
    {key:"LoadedData",value:"Loaded data"},
    {key:"InvalidHandle",value:"Invalid Handle"},
    {key:"YouHaveNotPermissionToPerformThisOperation",value:"You have not permission to perform this operation"},
    {key:"YouHaveNotPermissionToPerformThisOperationOrDataIsNotExists",value:"You have not permission to perform this operation or data is not exists"},
    {key:"ApprovedDataCannotBeDeleted",value:"Approved data cannot be deleted"},
    {key:"DateMonthYearDocument",value:"Date month year document"},
    {key:"NumberAndNotation",value:"Document number, notation"},
    {key:"ExpirationDate",value:"Expiration date"},
    {key:"DispatchArrivedNumber",value:"Dispatch arrived number"},
    {key:"Author",value:"Author"},
    {key:"UnitOrRecipientDocument",value:"Unit or recipient document"},
    {key:"CantCreateAccountWithSystemUsername",value:"Can't create account with system username"},
    {key:"AddFriend",value:"Add friend"},
    {key:"SearchYourFriendByIdOrName",value:"Search your friend by ID or their name"},
    {key:"SearchResults",value:"Searching Results"},
    {key:"FriendRequestHasBeenSent",value:"Friend request has been sent"},
    {key:"FriendRequest",value:"Friend request"},
    {key:"FriendList",value:"Friend list"},
    {key:"SendMessage",value:"Send message"},
    {key:"Customer",value:"Customer"},
    {key:"NewCustomer",value:"New Customer"},
    {key:"UpdateCustomer",value:"Update Customer"},
    {key:"All",value:"All"},
    {key:"Priority",value:"Priority"},
    {key:"Maintain",value:"Maintain"},
    {key:"Domain",value:"Domain"},
    {key:"Name",value:"Name"},
    {key:"Module",value:"Module"},
    {key:"ContactPerson",value:"Contact Person"},
    {key:"Contract",value:"Contract"},
    {key:"NewContract",value:"New Contract"},
    {key:"UpdateContract",value:"Update Contract"},
    {key:"UpdateContractExtension",value:"Update Contract Extension"},
    {key:"PotentialContract",value:"Potential Contract"},
    {key:"SpendingContract",value:"Spending"},
    {key:"CompletedContract",value:"Completed"},
    {key:"MaintainContract",value:"Maintain"},
    {key:"RegisterDate",value:"Register Date"},
    {key:"ExpirationDate",value:"Expiration Date"},
    {key:"Price",value:"Price"},
    {key:"SetupCost",value:"Setup Cost"},
    {key:"PackageModule",value:"Package Module"},
    {key:"ByMonth",value:"By Month"},
    {key:"ByYear",value:"By Year"},
    {key:"ContractValue",value:"Contract Value"},
    {key:"ContractExtension",value:"Contract Extension"},
    {key:"Package",value:"Package"},
    {key:"createdContract",value:"created Contract"},
    {key:"updatedContract",value:"updated Contract Information"},
    {key:"makeExtension",value:"make Contract Extension"},
    {key:"updatedExtension",value:"updated Contract Extension Information"},
    {key:"Phone",value:"Phone"},
    {key:"UploadFeatureImage",value:"UploadFeatureImage"},
    {key:"Product",value:"Product"},
    {key:"Quantity",value:"Quantity"},
    {key:"Draft",value:"Draft"},
    {key:"ShareWithMe",value:"Share With Me"},
    {key:"required",value:"required"},
    {key:"Week",value:"Week"},
    {key:"Day",value:"Day"},
    {key:"Days",value:"Days"},
    {key:"Month",value:"Month"},
    {key:"Year",value:"Year"},
    {key:"Quarter",value:"Quarter"},
    {key:"Select",value:"Select"},
    {key:"StartDate",value:"Start Date"},
    {key:"EndDate",value:"End Date"},
    {key:"MoreInfo",value:"More information"},
    {key:"Notes",value:"Notes"},
    {key:"Resource",value:"Resource"},
    {key:"Signed",value:"Signed"},
    {key:"PendingApproval",value:"Pending Approval"},
    {key:"SignedTransferTicket",value:"Signed transfer ticket"},
    {key:"Overdue",value:"Overdue"},
    {key:"OnSchedule",value:"On Schedule"},
    {key:"GonnaLate",value:"Gonna Late"},
    {key:"State",value:"State"},
    {key:"AddProof",value:"Added proof"},
    {key:"RemoveProof",value:"Removed proof"},
    {key:"RepeatEach",value:"Repeat each {{amount}}"},
    {key:"EndsOn",value:"Ends on"},
    {key:"WorkIsRepeatedCyclically",value:"Work is repeated Cyclically"},
    {key:"End",value:"End"},
    {key:"OnDay",value:"On day"},
    {key:"Never",value:"Never"},
    {key:"ParticipantList",value:"Participant List"},
    {key:"QRCode",value:"QR Code"},
    {key:"StudentId",value:"Student Id"},
    {key:"ClassId",value:"Class Id"},
    {key:"StudyProgramId",value:"Study Program Id"},
    {key:"CourseTime",value:"Course Time"},
    {key:"AckTrainingEventAction",value:"Did {{action}} for student id {{studentId}}"},
    {key:"Briefcase", value: "Briefcase"},
    {key:"BriefcaseTitle", value: "Briefcase title"},
    {key:"BriefcaseCode", value: "Briefcase code"},
    {key:"NumberAndNotationOfBriefcase", value: "Number And Notation Of Briefcase"},
    {key:"IdentifierCodeOfTheAgencyOrOrganizationCompilingTheBriefcaseInventory", value: "Identifier code of the agency or organization compiling the briefcase inventory."},
    {key:"UsageMode", value:"Usage mode"},
    {key:"Language", value:"Language"},
    {key:"StorageDuration", value:"Storage duration"},
    {key:"TotalPageOfBriefcase", value:"Total page of briefcase"},
    {key:"TotalDocumentOfBriefcase", value:"Total document of briefcase"},
    {key:"Warning", value:"Warning"},
    {key:"Expired", value:"Expired"},
    {key:"ProofOrCommentIsRequiredForTheTask", value:"Proof or comment is required for the task to be marked as 'Completed'"},
    {key:"SubmissionDepartment", value:"submission Department"},
    {key:"signedDate", value:"Signed date"},
    {key:"HostPerson", value:"Host person"},
    {key:"RecipientToKnowPerson", value:"Recipient to know person"},
    {key:"NotPublicYet", value:"Not public yet"},
    {key:"OrganizationEdit", value:"Organization Edit"},
    {key:"Released", value:"Released"},
    {key:"Message", value:"Message"},
    {key:"Dear", value:"Dear"},
    {key:"Receiver", value:"Receiver"},
    {key:"Release", value:"Release"},
    {key:"SuccessExecuting", value:"Success Executing"},
    {key:"Executing...", value:"Executing..."},
    {key:"ReceivingDepartment", value:"Receiving Department"},
    {key:"DocumentNeedToBeExploited", value:"Documents need to be exploited"},
    {key:"SignToAcknowledge", value:"Sign to acknowledge"},
    {key:"Are you sure you want to sign acknowledge?", value:"Are you sure you want to sign acknowledge?"},
    {key:"SignedToAcknowledge", value:"Signed to acknowledge"},
    {key:"InputTitle", value:"Input title"},
    {key:"InputAuthor", value:"Input author"},
    {key:"InputNote", value:"Input note"},
    {key:"NumberCodeDocument", value:"Number and Code Document"},
    {key:"DateDocument", value:"Document Date"},
    {key:"TypeDocumentAndExcerpt", value:"Document Type and Excerpt"},
    {key:"ReceivingDocumentDepartment", value:"Receiving Document Department"},
    {key:"OutgoingDocuments", value:"Outgoing Documents"},
    {key:"AttachDocuments", value:"Attach Documents"},
    {key:"StorageName", value:"Storage Name"},
    {key:"StorageLocation", value:"Storage Location"},
    {key:"RelatedInformation", value:"Related Information"},
    {key:"TypeName", value:"Type Name"},
    {key:"DocumentQuantity", value:"Document Quantity"},
    {key:"TransferDate", value:"Transfer Date"},
    {key:"InvalidAction", value:"Invalid Action"},
    {key:"ReceiverOrDepartmentNotificationIsRequired", value:"Receiver or Department Notification is required"},
    {key:"InputQuantity", value:"Input Quantity"},
    {key:"PageNotFoundLine1", value:"Page not found"},
    {key:"PageNotFoundLine2", value:"The page you are looking for could not be found or you don't have permission to access this page. Please contact the administrator for further assistance."},
    {key:"NoPermissionLine1", value:"Access Denied"},
    {key:"NoPermissionLine2", value:"Sorry, you do not have permission to access this page. Please check your access rights or contact the administrator for further assistance."},
    {key:"CanNotAssignMultipleMainPerson", value:"Only one main person can be assigned to a task"},
    {key:"MainPersonRequired", value:"Main person is required"},
    {key:"Input quantity", value:"Input quantity"},
    {key:"DoYouWantReleaseODB", value:"Do you want to release the outgoing dispatch?"},
    {key:"ArrivedDate", value:"Arrived Date"},
    {key:"ReceivingUnit", value:"Receiving Unit"},
    {key:"BriefCase",value:"BriefCase"},
    {key:"NumberOfArrivedBook",value: "Number of arrived book"},
    {key:"OutgoingReferenceNumber",value: "Outgoing reference number"},
    {key:"functionApply",value: "Function Apply"},
    {key:"chooseColor",value: "Choose color"},
    {key:"Fixed",value: "Fixed"},
    {key:"Flexible",value: "Flexible"},
    {key:"Handling methods",value: "Handling methods"},
    {key:"Select an Option",value: "Select an Option"},
    {key:"Received",value:"Received"},
    {key:"TransactionNotificationReceived",value:"Transaction Notification Received"},
    {key:"Automaticallycompletethetask",value:"Automatically complete the task"},
    {key:"ArchiveProfileComplete",value:"Archive Profile Complete"},
    {key:"task",value:"Task"},
    {key:"dispatch_arrived",value:"Dispatch Arrived"},
    {key:"workflow_play",value:"Workflow Play"},
    { key: "IsRepetitiveTask", value: "Is repetitive task" },
    { key: "WholeSchool", value: "WholeSchool" },
    { key: "SendTo", value: "Send to" },
    { key: "GeneralInformation", value: "General information" },
    {key:"ApproveForm",value:"Approve form"},
    { key: "ApprovedToCreate", value: "Approved to create" },
    { key: "ApprovedToShow", value: "Approved to show" },
    { key: "Bookmark", value: "Bookmark" },
    {key:"NeedToHandleLevel_1",value:"Leader need to handle"},
    {key:"NeedToHandleLevel_2",value:"Department leader need to handle"},
    {key:"Scope",value:"Scope"},
    {key:"External",value:"External"},
    {key:"Internal",value:"Internal"},
    // OCR
    {key:"Modification Action", value:"Modification Action"},
    {key:"Add Row/Column", value:"Add Row/Column"},
    {key:"Remove Row/Column", value:"Remove Row/Column"},
    {key:"Apply Regex", value:"Apply Regex"},
    {key:"Split by Regex", value:"Split by Regex"},
    {key:"Merge tables", value:"Merge tables"},
    {key:"Split tables", value:"Split tables"},
    {key:"Arithmetic", value:"Arithmetic"},
    {key:"Merge", value:"Merge"},
    {key:"Copy", value:"Copy"},
    {key:"Add Type", value:"Add Type"},
    {key:"Remove Type", value:"Remove Type"},
    {key:"Row Values (comma-separated)", value:"Row Values (comma-separated)"},
    {key:"Value1, Value2, ...", value:"Value1, Value2, ..."},
    {key:"Row Position", value:"Row Position"},
    {key:"Enter row position (0 for top)", value:"Enter row position (0 for top)"},
    {key:"Column Default Value", value:"Column Default Value"},
    {key:"Default value for column", value:"Default value for column"},
    {key:"Column Position", value:"Column Position"},
    {key:"Enter column position (0 for leftmost)", value:"Enter column position (0 for leftmost)"},
    {key:"Row Indices to Remove (comma-separated)", value_vn:"Row Indices to Remove (comma-separated)"},
    {key:"Column Index to Remove", value_vn:"Column Index to Remove"},
    {key:"Cell Coordinates (Row,Column)", value:"Cell Coordinates (Row,Column)"},
    {key:"New Cell Value", value:"New Cell Value"},
    {key:"Enter new value", value:"Enter new value"},
    {key:"Arithmetic Operation", value:"Arithmetic Operation"},
    {key:"Addition (+)", value:"Addition (+)"},
    {key:"Subtraction (-)", value:"Subtraction (-)"},
    {key:"Multiplication (*)", value:"Multiplication (*)"},
    {key:"Division (/)", value:"Division (/)"}, 
    {key:"Choose the operation to perform between the specified indices.", value:"Choose the operation to perform between the specified indices."},
    {key:"Operation Type", value:"Operation Type"},
    {key:"Specify whether the operation applies to rows or columns.", value:"Specify whether the operation applies to rows or columns."},
    {key:"Index A", value:"Index A"},
    {key:"Enter Index A (starting from 0)", value:"Enter Index A (starting from 0)"},
    {key:"Example: 0 (Index for the first row/column for the operation).", value:"Example: 0 (Index for the first row/column for the operation)."},
    {key:"Index B", value:"Index B"},
    {key:"Enter Index B (starting from 0)", value:"Enter Index B (starting from 0)"},
    {key:"Example: 1 (Index for the second row/column for the operation).", value:"Example: 1 (Index for the second row/column for the operation)."},
    {key:"Target Index", value:"Target Index"},
    {key:"Enter Target Index (starting from 0)", value:"Enter Target Index (starting from 0)"},
    {key:"Example: 2 (Index where the result will be stored).", value:"Example: 2 (Index where the result will be stored)."},
    {key:"Select a Popular Regex Pattern", value:"Select a Popular Regex Pattern"},
    {key:"-- Select a regex pattern --", value:"-- Select a regex pattern --"},
    {key:"Or Enter Custom Regex", value:"Or Enter Custom Regex"},
    {key:"Enter regex pattern", value:"Enter regex pattern"},
    {key:"Column Index", value:"Column Index"},
    {key:"Index of column to apply regex", value:"Index of column to apply regex"},
    {key:"Enable Filter Mode", value:"Enable Filter Mode"},
    {key:"Column Index", value:"Column Index"},
    {key:"Enter column index", value:"Enter column index"},
    {key:"Regex", value:"Regex"},
    {key:"Split Mode", value:"Split Mode"},
    {key:"Split into Columns", value:"Split into Columns"},
    {key:"Split into Rows", value:"Split into Rows"},
    {key:"Split by rows with missing data", value:"Split by rows with missing data"},
    {key:"Separator (Optional)", value:"Separator (Optional)"},
    {key:"Enter separator", value:"Enter separator"},
    {key:"Start Cell:", value:"Start Cell:"},
    {key:"End Cell:", value:"End Cell:"},
    {key:"Copy Mode", value:"Copy Mode"},
    {key:"Column to column", value:"Column to column"},
    {key:"Row to row", value:"Row to row"},
    {key:"Index:", value:"Index:"},
    {key:"Target", value:"Target"},
    {key:"Paste To", value:"Paste To"},
    {key:"Add Modification", value:"Add Modification"},
    {key:"Current Modifications", value:"Current Modifications"},
    {key:"Note:", value:"Note:"},
    {key:"Modifications will be executed from top to bottom. You can reorder them to change the execution sequence.", value:"Modifications will be executed from top to bottom. You can reorder them to change the execution sequence."},
    {key:"Action", value:"Action"},
    {key:"Details", value:"Details"},
    {key:"Index", value:"Index"},
    {key:"Split Mode", value:"Split Mode"},
    {key:"Filter", value:"Filter"},
    {key:"Column", value:"Column"},
    {key:"Row", value:"Row"},
    {key:"Actions", value:"Actions"},
    {key:"Save Changes", value:"Save Changes"},
    {key:"Apply Modification for Test", value:"Apply Modification for Test"},
    {key:"Manage Modifications", value:"Manage Modifications"},
    {key:"From Date must be less than To Date", value:"From Date must be less than To Date"},
    {key:"Please select the document to export", value:"Please select the document to export"},
    {key:"Document Data Preview", value:"Document Data Preview"},

    
    
    
    {key:"InsertBundleErrorMessage", value:"An error occurred while creating a new bundle!"},
    {key:"Are you sure you want to delete this bundle?", value: "Are you sure you want to delete this bundle?"},
    {key:"InsertBundleErrorMessage", value:"An error occurred while deleting a bundle!"},
    {key:"Create New Document Type", value:"Create New Document Type"},
    {key:"Visible Items", value:"Visible Items"},
    {key:"DocumentTypeName", value: "Document Type Name"},
    {key:"DocumentTypeDescription", value:"Document Type Description"},
    {key:"Upload Documents", value:"Upload Documents"},
    {key:"Number of Documents", value:"Number of Documents"},
    {key:"Document Name", value:"Document Name"},
    {key:"ScanDocument", value:"Scan Selected Document"},
    {key:"ScanStatus", value:"Document scan status"},
    {key:"OCR Template Note", value: "For each document type, please upload a template and define rules for it. Once a template and its rules are set, any additional documents uploaded in this document type will automatically inherit these template rules as defaults."},
    {key:"You can modify rules for each individual document later if needed.", value:"You can modify rules for each individual document later if needed."},
    {key:"Processed",value:"Processed"},
    {key:"Not Processed", value:"Not Processed"},
    {key:"Extract Status", value:"Extract Status"},
    {key:"Extracted Data", value:"Extracted Data"},
    {key:"Extracted Data From Template", value:"Extracted Data From Template"},
    {key:"Field Name", value:"Field Name"},
    {key:"Coordinates", value:"Coordinates"},
    {key:"Upload Template", value:"Upload Template"},
    {key:"Zoom", value:"Zoom"},
    {key:"Zoom In", value:"Zoom In"},
    {key:"Zoom Out", value:"Zoom Out"},
    {key:"Real Size", value:"Real Size"},
    {key:"Enter field name", value:"Enter field name"},
    {key:"Page", value:"Page"},
    {key:"Add Rule", value:"Add Rule"},
    {key:"Post-Process", value:"Post-Process"},
    {key:"Saving...", value:"Saving..."},
    {key:"Loading...", value:"Loading...."},
    {key:"Verify Rule on Template", value:"Verify Rule on Template"},
    {key:"Verifying...", value:"Verifying..."},
    {key:"Hide Grid", value:"Hide Grid"},
    {key:"Show Grid", value:"Show Grid"},
    {key:"Hide Details", value:"Hide Details"},
    {key:"Show Details", value:"Show Details"},
    {key:"Hide Document Content", value:"Hide Document Content"},
    {key:"Show Document Content", value:"Show Document Content"},
    {key:"You have unsaved changes. Please save your work.", value:"You have unsaved changes. Please save your work."},
    {key:"Upload Testing Files",value:"Upload Testing Files"},
    {key:"Ensure that all rules in the popup window are defined correctly. Remember to save your rules before leaving this page or when you're confident the rules work correctly for the template.",value:"Ensure that all rules in the popup window are defined correctly. Remember to save your rules before leaving this page or when you're confident the rules work correctly for the template."},
    {key:"Upload Testing Files",value:"Upload Testing Files"},
    {key:"When you upload a testing file, the system will automatically run OCR on the uploaded document using the temporary rules defined in the popup window to verify their accuracy.",value:"When you upload a testing file, the system will automatically run OCR on the uploaded document using the temporary rules defined in the popup window to verify their accuracy."},
    {key:"Are you sure you want to delete this document?",value:"Are you sure you want to delete this document?"},
    {key:"Upload Document",value:"Upload Document"},
    {key:"Delete Document",value:"Delete Document"},
    {key:"Table Data and Modifications",value:"Table Data and Modifications"},
    {key:"Raw Table Data",value:"Raw Table Data"},
    {key:"Post-Processed Table Data",value:"Post-Processed Table Data"},
    {key:"No post-processed table data available. Apply modifications to generate.",value:"No post-processed table data available. Apply modifications to generate."},

    
    {key:"No Document Type found",value:"No Document Type found"},
    {key:"Display", value:"Display"},
    {key:"Uploading template...", value:"Uploading template..."},
    {key:"Note: When uploading a test file, the system will automatically use the temporary rules in the popup to verify the accuracy of the uploaded document. Make sure to save the rules before leaving the page or when you're confident they work correctly.", value:"Note: When uploading a test file, the system will automatically use the temporary rules in the popup to verify the accuracy of the uploaded document. Make sure to save the rules before leaving the page or when you're confident they work correctly."},
    {key:"Use AI for Processing", value:"Use AI for Processing"}
];
