module.exports=[
    {key:"Me",value:"Tôi"},
    {key:"public",value:"Cộng đồng"},
    {key:"pending",value:"đang xử lý"},
    {key:"Events",value:"Các sự kiện"},
    {key:"created",value:"Đã tạo"},
    {key:"updated",value:"Đã cập nhật"},
    {key:"Project",value:"Dự án"},
    {key:"NewProject",value:"Thêm mới dự án"},
    {key:"WikiNew",value:"Thêm mới Wiki"},
    {key:"WikiUpdate",value:"Cập nhật Wiki"},
    {key:"DBName",value:"Tên Database"},
    {key:"Collection",value:"Collection"},
    {key:"Time",value:"Thời gian"},
    {key:"WrittenBy",value:"Được soạn thảo bởi"},
    {key:"SaveBy",value:"được lưu bởi"},
    {key:"Name",value:"Tên"},
    {key:"Display",value:"Hiển thị"},
    {key:"DoYouWantToDeleteFollowData",value:"Bạn có muốn xoá các dữ liệu sau"},
    {key:"Activate",value:"Hoạt động"},
    {key:"Deactivate",value:"Vô hiệu hoá"},
    {key:"Branch",value:"Chi nhánh"},
    {key:"Competence",value:"Quyền hạn"},
    {key:"NotSelectedYet",value:"Chưa chọn"},
    {key:"Pick",value:"Chọn"},
    {key:"AttachedFile",value:"Tệp đã đính kèm"},
    {key:"UploadFile",value:"Tải tệp lên"},
    {key:"UploadFolder",value:"Tải thư mục lên"},
    {key:"DragTheFileHereToUpload",value:"Kéo tệp vào đây để tải lên"},
    {key:"DragTheFolderHereToUpload",value:"Kéo thư mục vào đây để tải lên"},
    {key:"TheFileWillAutomaticallyUploadWhenSelected",value:"Tệp sẽ tự động tải lên khi chọn"},
    {key:"UploadImage",value:"Tải ảnh lên"},
    {key:"DragTheImageHereToUpload",value:"Kéo ảnh vào đẩy để tải lên"},
    {key:"DetailsInformation",value:"Thông tin chi tiết"},
    {key:"Approval",value:"Chấp thuận"},
    {key:"Approve",value:"Duyệt"},
    {key:"SignOther",value:"Ký thừa lệnh"},
    {key:"Reject",value:"Bác bỏ"},
    {key:"Approving",value:"Đang phê duyệt"},
    {key:"Rejecting",value:"Đang bác bỏ"},
    {key:"SuccessApproval",value:"Đã chấp thuận"},
    {key:"SuccessReject",value:"Đã bác bỏ"},
    {key:"SuccessReturn",value:"Đã trả lại"},
    {key:"SuccessResubmit",value:"Đã gửi lại"},
    {key:"SuccessSign",value:"Thực hiện ký thành công"},
    {key:"All",value:"Tất cả"},
    {key:"Bookmark",value:"Đã lưu"},
    {key:"Pending",value:"Đang xử lý"},
    {key:"ApprovedByDepartmentLeader",value:"Trưởng bộ phận đã duyệt"},
    {key:"Spending",value:"Chi tiêu"},
    {key:"Processing",value:"Chưa hoàn thành"},
    {key:"PleaseCheckInformation",value:"Xin kiểm tra lại thông tin"},
    {key:"DataIsNull",value:"Dữ liệu không tồn tại"},
    {key:"ExistAccount",value:"Tài khoản đã được sử dụng"},
    {key:"Register",value:"Đăng ký"},
    {key:"Workflow",value:"Quy trình"},
    {key:"DocumentType",value:"Loại tài liệu"},
    {key:"TypeName",value:"Tên loại"},
    {key:"TemplateFile",value:"Tệp tin mẫu"},
    {key:"ApprovalType",value:"Loại phê duyệt"},
    {key:"Signing",value:"Quy Trình"},
    {key:"WorkflowForMe",value:"Quy trình giành cho tôi"},
    {key:"FeaturePopular",value:"Tính năng thông dụng"},
    {key:"WorkflowPlay",value:"Quy Trình"},
    {key:"ApproverIsNull",value:"Người phê duyệt không tồn tại"},
    {key:"Created",value:"Đã tạo"},
    {key:"Updated",value:"Đã cập nhật"},
    {key:"Approved",value:"Đã phê duyệt"},
    {key:"ApprovedToCreate",value:"Đã phê duyệt khởi tạo"},
    {key:"Handled",value:"Đã xử lý"},
    {key:"Approver",value:"Người phê duyệt"},
    {key:"Rejected",value:"Đã bác bỏ"},
    {key:"Returned",value:"Đã trả lại"},
    {key:"SaveODB",value:"Đã lưu sổ công văn đi"},
    {key:"SaveBriefCase",value:"Đã lưu Hồ sơ"},
    {key:"transformSign",value:"Đã giao ký thừa lệnh cho"},
    {key:"NeedToHandle",value:"Cần xử lý"},
    {key:"FileSigning",value:"Tệp tin trình ký"},
    {key:"RelatedFile",value:"Tệp tin liên quan"},
    {key:"Note",value:"Ghi chú"},
    {key:"InputNote",value:"Nhập nội dung ghi chú"},
    {key:"YourLanguage",value:"Ngôn ngữ của bạn"},
    {key:"Task",value:"Công việc"},
    {key:"Assigned",value:"Được giao"},
    {key:"FromDate",value:"Từ ngày"},
    {key:"ToDate",value:"Đến ngày"},
    {key:"Grade",value:"Cấp"},
    {key:"MainPerson",value:"Người chịu trách nhiệm"},
    {key:"Participant",value:"Người tham gia"},
    {key:"Observer",value:"Người giám sát"},
    {key:"NotStartedYet",value:"Chưa bắt đầu"},
    {key:"Responsibility",value:"Chịu trách nhiệm"},
    {key:"StartDoing",value:"Bắt đầu thực hiện"},
    {key:"Completed",value:"Hoàn thành"},
    {key:"Unfinished",value:"Chưa hoàn thành"},
    {key:"Comment",value:"Bình luận"},
    {key:"PostAComment",value:"Đăng bình luận"},
    {key:"SuccessUpdating",value:"Cập nhật thành công"},
    {key:"LeaveForm",value:"Đơn nghỉ phép"},
    {key:"NumberOfDays",value:"Số ngày"},
    {key:"Reason",value:"Lý do"},
    {key:"days",value:"ngày"},
    {key:"DispatchArrived",value:"Công văn đến"},
    {key:"DispatchOutgoing",value:"Công văn đi"},
    {key:"DispatchArrivedType",value:"Tên loại"},
    {key:"DispatchArrivedBook",value:"Sổ công văn đến"},
    {key:"EmergencyLevel",value:"Độ khẩn"},
    {key:"ReceiveMethod",value:"Phương thức nhận"},
    {key:"SendMethod",value:"Phương thức gửi"},
    {key:"Excerpt",value:"Trích yếu"},
    {key:"DispatchArrivedDate",value:"Ngày chuyển"},
    {key:"Transfer date",value:"Ngày chuyển"},
    {key:"OutgoingDispatchBookDate",value:"Ngày công văn đi"},
    {key:"SaveDispatchBook",value:"Lưu sổ công văn"},
    {key:"DateMonthYearDocument",value:"Ngày tháng năm văn bản"},
    {key:"Author",value:"Tác giả"},
    {key:"UnitOrRecipientDocument",value:"Đơn vị hoặc người nhận văn bản"},
    {key:"ReleaseDate",value:"Thời gian phát hành"},
    {key:"PlaceOfDispatchArrived",value:"Nơi gửi"},
    {key:"TheSigner",value:"Người ký"},
    {key:"IsLegalDocument",value:"Là văn bản quy phạm pháp luật"},
    {key:"IsTheAssignmentDocument",value:"Là văn bản giao nhiệm vụ"},
    {key:"PeopleHandling",value:"Người xử lý"},
    {key:"AtLeast",value:"Nhỏ nhất là {{title}}"},
    {key:"Number",value:"Số"},
    {key:"Handling",value:"Xử trí"},
    {key:"Forward",value:"Chuyển tiếp"},
    {key:"AddTaskForThis",value:"Thêm công việc"},
    {key:"AddNotifyForThis",value:"Thêm thông báo"},
    {key:"NotRequired",value:"không bắt buộc"},
    {key:"InvalidInformation",value:"Thông tin không hợp lệ"},
    {key:"HandlingAndForward",value:"Xử lý và chuyển tiếp"},
    {key:"to",value:"đến"},
    {key:"Action",value:"Hành động"},
    {key:"Seen",value:"Đã xem"},
    {key:"NotSeen",value:"Chưa xem"},
    { key: "Employee", value: "Nhân viên" },
    {key:"WholeSchool",value:"Toàn trường"},
    {key:"Sent",value:"Đã gửi"},
    {key:"Notice",value:"Lưu ý"},
    {key:"Reportscanonlybesentfrom3amto9am",value:"Chỉ có thể gửi và chỉnh sửa báo cáo từ 3 giờ sáng đến 9 giờ sáng"},
    {key:"Reportscanonlybesentfromto",value:"Chỉ có thể gửi và chỉnh sửa báo cáo từ {{from}} giờ đến {{to}} giờ"},
    {key:"TotalNurse_Technicians",value:"Tổng số điều dưỡng/ kỹ thuật viên"},
    {key:"NurseReport",value:"Báo cáo điều dưỡng"},
    {key:"MyJourneyTimeForm",value:"Giấy đi đường của tôi"},
    {key:"ExceptTimeOnRoad",value:"Trừ thời gian đi đường"},
    {key:"AddJourneyTimeForm",value:"Tạo giấy đi đường"},
    {key:"CancelJourneyTimeForm",value:"Huỷ tạo giấy đi đường"},
    {key:"Cancel",value:"Huỷ"},
    {key:"AdministrativeNursing_Technicians",value:"Điều dưỡng/ kỹ thuật viên hành chính"},
    {key:"OutShiftNursing_Technicians",value:"Điều dưỡng/kỹ thuật viên ngoài tua trực"},
    {key:"NursingOutHospital",value:"Điều dưỡng ngoại viện"},
    {key:"MorningShiftNursing",value:"Điều dưỡng trực sáng"},
    {key:"AfternoonShiftNursing",value:"Điều dưỡng trực chiều"},
    {key:"NightShiftNursing",value:"Điều dưỡng trực đêm"},
    {key:"OverShiftNursing",value:"Điều dưỡng 24/24"},
    {key:"LeaveShiftNursing",value:"Điều dưỡng ra trực"},
    {key:"NursingAtClinic",value:"Điều dưỡng tại phòng khám"},
    {key:"LeaveNursing",value:"Điều dưỡng nghỉ phép"},
    {key:"MaternityLeaveNursing",value:"Điều dưỡng nghỉ hậu sản"},
    {key:"SickLeaveNursing",value:"Điều dưỡng nghỉ bệnh"},
    {key:"NursingGoSchool",value:"Điều dưỡng đi học"},
    {key:"ApprenticeNursing",value:"Điều dưỡng học việc"},
    {key:"ProbationaryNursing",value:"Điều dưỡng thử việc"},
    {key:"OtherCase",value:"Trường hợp khác"},
    {key:"RealBed",value:"Giường thực kê"},
    {key:"PatientNumber",value:"Tổng số bệnh nhân"},
    {key:"Level1Care",value:"Chăm sóc cấp 1"},
    {key:"FinalPhasePatient",value:"Bệnh nhân giai đoạn cuối"},
    {key:"VentilatorBase",value:"Cơ số máy thở"},
    {key:"ActiveVentilator",value:"Máy thở đang sử dụng"},
    {key:"MonitorBase",value:"Cơ số monitor"},
    {key:"ActiveMonitor",value:"Monitor đang sử dụng"},
    {key:"ElectricSyringeBase",value:"Cơ số bơm tiêm"},
    {key:"ActiveElectricSyringe",value:"Bơm tiêm đang sử dụng"},
    {key:"DropsCounterBase",value:"Cơ số máy đếm giọt"},
    {key:"ActiveDropsCounter",value:"Máy đếm giọt đang sử dụng"},
    {key:"General",value:"Chung"},
    {key:"Module",value:"Module"},
    {key:"Report",value:"Báo cáo"},
    {key:"Statistic",value:"Thống kê"},
    {key:"Date",value:"Ngày"},
    {key:"Sum",value:"Tổng"},
    {key:"ThingsNeedToHandle",value:"Công việc cần xử lý"},
    {key:"NotReportYet",value:"Chưa báo cáo"},
    {key:"LoadMoreNotify",value:"Tải thêm thông báo"},
    {key:"Password",value:"Mật khẩu"},
    {key:"NewPassword",value:"Mật khẩu mới"},
    {key:"RetypeNewPassword",value:"Nhập lại mật khẩu mới"},
    {key:"UpdateSuccessed",value:"Cập nhật thành công"},
    {key:"ChangePasswordSuccessed",value:"Thay đổi mật khẩu thành công"},
    {key:"TryToUseNewPassword",value:"Hãy sử dụng mật khẩu mới"},
    {key:"MyProfile",value:"Hồ sơ của tôi"},
    {key:"BasicSalary",value:"Lương cơ bản"},
    {key:"Salary",value:"Lương"},
    {key:"NumberOfHours",value:"Số giờ"},
    {key:"SalaryHours",value:"Giờ lương"},
    {key:"Hours",value:"Giờ"},
    {key:"Applicable for main person only",value:"Chỉ áp dụng cho người chịu trách nhiệm"},
    {key:"NotCompleted",value:"Chưa hoàn thành"},
    {key:"OutDeadline",value:"Trễ hạn"},
    {key:"Done",value:"Làm xong"},
    {key:"DoneDone",value:"Xong"},
    {key:"WaitingForApproval",value:"Chờ phê duyệt"},
    {key:"Approve",value:"Phê duyệt"},
    {key:"Close",value:"Đóng"},
    {key:"CreatedChildTask",value:"Đã thêm công việc con"},
    {key:"ChildTask",value:"Công việc con"},
    {key:"ParentTask",value:"Công việc cha"},
    {key:"Staff",value:"Nhân viên"},
    {key:"UpdatedInformation",value:"Đã cập nhật thông tin"},
    {key:"BirthDay",value:"Sinh nhật"},
    {key:"DateOfBirth",value:"Ngày sinh"},
    {key:"SelfDeclaration",value:"Tự khai báo"},
    {key:"EmployeeCode",value:"Mã nhân viên"},
    {key:"DuplicateData",value:"Dữ liệu trùng"},
    {key:"LoadedData",value:"Dữ liệu đã tải lên"},
    {key:"InvalidHandle",value:"Thao tác không hợp lệ"},
    {key:"YouHaveNotPermissionToPerformThisOperation",value:"Bạn không có quyền thực hiện thao tác này"},
    {key:"YouHaveNotPermissionToPerformThisOperationOrDataIsNotExists",value:"Bạn không có quyền thực hiện thao tác này hoặc dữ liệu không tồn tại"},
    {key:"ApprovedDataCannotBeDeleted",value:"Không thể xoá dữ liệu đã được phê duyệt"},
    {key:"NumberAndNotation",value:"Số, ký hiệu văn bản"},
    {key:"DateMonthYearDocument",value:"Ngày tháng năm văn bản"},
    {key:"ExpirationDate",value:"Thời hạn"},
    {key:"DispatchArrivedNumber",value:"Số đến"},
    {key:"Author",value:"Tác giả"},
    {key:"UnitOrRecipientDocument",value:"Đơn vị hoặc người nhận văn bản"},
    {key:"CantCreateAccountWithSystemUsername",value:"Không được tạo tài khoản với username hệ thống"},
    {key:"AddFriend",value:"Thêm bạn"},
    {key:"SearchYourFriendByIdOrName",value:"Tìm bạn bằng ID hoặc tên"},
    {key:"SearchResults",value:"Kết quả tìm kiếm"},
    {key:"FriendRequestHasBeenSent",value:"Lời mời kết bạn đã gửi"},
    {key:"FriendRequest",value:"Yêu cầu kết bạn"},
    {key:"FriendList",value:"Danh sách bạn bè"},
    {key:"SendMessage",value:"Gửi tin nhắn"},
    {key:"Customer",value:"Khách hàng"},
    {key:"NewCustomer",value:"Thêm khách hàng"},
    {key:"UpdateCustomer",value:"Cập nhật thông tin khách hàng"},
    {key:"Priority",value:"Độ ưu tiên"},
    {key:"Maintain",value:"Bảo trì"},
    {key:"Domain",value:"Tên miền"},
    {key:"Name",value:"Tên"},
    {key:"Module",value:"Module"},
    {key:"ContactPerson",value:"Người liên hệ"},
    {key:"Contract",value:"Hợp đồng"},
    {key:"NewContract",value:"Tạo mới hợp đồng"},
    {key:"UpdateContract",value:"Cập nhật thông tin hợp đồng"},
    {key:"UpdateContractExtension",value:"Cập nhật hợp đồng gia hạn"},
    {key:"PotentialContract",value:"Tiềm năng"},
    {key:"SpendingContract",value:"Chờ thanh toán"},
    {key:"CompletedContract",value:"Đã thanh toán"},
    {key:"MaintainContract",value:"Bảo trì"},
    {key:"TrashContract",value:"Xóa"},
    {key:"RegisterDate",value:"Ngày đăng ký"},
    {key:"Price",value:"Giá"},
    {key:"SetupCost",value:"Chi phí cài đặt"},
    {key:"PackageModule",value:"Gói sản phẩm"},
    {key:"ByMonth",value:"Theo tháng"},
    {key:"ByYear",value:"Theo năm"},
    {key:"ContractValue",value:"Giá trị hợp đồng"},
    {key:"ContractExtension",value:"Gia hạn hợp đồng"},
    {key:"Package",value:"Gói"},
    {key:"createdContract",value:"đã tạo hợp đồng"},
    {key:"updatedContract",value:"đã cập nhật thông tin hợp đồng"},
    {key:"makeExtension",value:"đã gia hạn hợp đồng"},
    {key:"updatedExtension",value:"đã cập nhật thông tin gia hạn hợp đồng"},
    {key:"Phone",value:"Số điện thoại"},
    {key:"UploadFeatureImage",value:"Kéo tệp vào đây để tải lên"},
    {key:"Product",value:"Sản phẩm"},
    {key:"Quantity",value:"Số lượng"},
    {key:"Draft",value:"Nháp"},
    {key:"ShareWithMe",value:"Chia Sẽ Với Tôi"},
    {key:"required",value:"bắt buộc"},
    {key:"Week",value:"Tuần"},
    {key:"Day",value:"Ngày"},
    {key:"Days",value:"Ngày"},
    {key:"Month",value:"Tháng"},
    {key:"Year",value:"Năm"},
    {key:"Quarter",value:"Quý"},
    {key:"Select",value:"Chọn"},
    {key:"StartDate",value:"Thời gian bắt đầu"},
    {key:"EndDate",value:"Thời gian kết thúc"},
    {key:"MoreInfo",value:"Xem thêm thông tin"},
    {key:"Notes",value:"Ghi chú"},
    {key:"Resource",value:"Nguồn lực"},
    {key:"Signed",value:"Đã ký"},
    {key:"Forwarded",value:"Đã chuyển tiếp"},
    {key:"PendingApproval",value:"Chờ chấp thuận"},
    {key:"SignedTransferTicket",value:"Đã ký phiếu chuyển"},
    {key:"Overdue",value:"Trễ hạn"},
    {key:"Open",value:"Còn hạn"},
    {key:"OnSchedule",value:"Đúng hạn"},
    {key:"GonnaLate",value:"Sắp tới hạn"},
    {key:"Early",value:"Sớm hạn"},
    {key:"Late",value:"Hoàn thành trễ hạn"},
    {key:"State",value:"Tình trạng"},
    {key:"AddProof",value:"Đã thêm minh chứng"},
    {key:"RemoveProof",value:"Đã xóa minh chứng"},
    {key:"RepeatEach",value:"Lặp lại mỗi {{amount}}"},
    {key:"EndsOn",value:"Kết thúc vào"},
    {key:"WorkIsRepeatedCyclically",value:"Công việc được lặp lại theo chu kỳ"},
    {key:"End",value:"Kết thúc"},
    {key:"OnDay",value:"Vào ngày"},
    {key:"Never",value:"Không bao giờ"},
    {key:"ParticipantList",value:"Danh sách tham gia"},
    {key:"QRCode",value:"Mã QR"},
    {key:"StudentId",value:"Mã Sinh Viên"},
    {key:"ClassId",value:"Mã Lớp"},
    {key:"StudyProgramId",value:"Mã chương trình đào tạo"},
    {key:"CourseTime",value:"Khóa"},
    {key:"AckTrainingEventAction",value:"Đã {{action}} cho mã sinh viên {{studentId}}"},
    {key:"Briefcase", value: "Bìa hồ sơ"},
    {key:"BriefcaseTitle", value: "Tiêu đề bìa hồ sơ"},
    {key:"BriefcaseCode", value: "Mã hồ sơ"},
    {key:"NumberAndNotationOfBriefcase", value: "Số và ký hiệu hồ sơ"},
    {key:"IdentifierCodeOfTheAgencyOrOrganizationCompilingTheBriefcaseInventory", value: "Mã định danh của cơ quan, tổ chức lập danh mục hồ sơ"},
    {key:"UsageMode", value:"Chế độ sử dụng"},
    {key:"Language", value:"Ngôn ngữ"},
    {key:"StorageDuration", value:"Thời gian bảo quản"},
    {key:"TotalPageOfBriefcase", value:"Tổng số trang trong hồ sơ"},
    {key:"TotalDocumentOfBriefcase", value:"Tổng số văn bản trong hồ sơ"},
    {key:"day", value:"ngày"},
    {key:"month", value:"tháng"},
    {key:"year", value:"năm"},
    {key:"vi-VN", value:"tiếng Việt"},
    {key:"Note", value:"ghi chú"},
    {key:"Expired", value:"Hết hạn"},
    {key:"Warning", value:"Cảnh báo"},
    {key:"Employees", value:"Nhân viên"},
    {key:"ProofOrCommentIsRequiredForTheTask", value:"Công việc cần có minh chứng hoặc bình luận để thay đổi sang đã 'Hoàn thành'"},
    {key:"CurrentTask", value:"Công việc hiện tại"},
    {key:"CompletedTask", value:"Công việc đã hoàn thành"},
    {key:"SubmissionDepartment", value:"Đơn vị soạn"},
    {key:"signedDate", value:"Ngày ký"},
    {key:"HostPerson", value:"Người chủ trì"},
    {key:"RecipientToKnowPerson", value:"Người nhận để biết"},
    {key:"NotPublicYet", value:"Chưa phát hành"},
    {key:"OrganizationEdit", value:"Đơn vị soạn"},
    {key:"Released", value:"Đã phát hành"},
    {key:"Message", value:"Thông điệp"},
    {key:"Dear", value:"Kính gửi"},
    {key:"Receiver", value:"Người nhận"},
    {key:"Release", value:"Phát hành"},
    {key:"SuccessExecuting", value:"Thực hiện thành công"},
    {key:"Executing...", value:"Đang thực hiện..."},
    {key:"ReceivingDepartment", value:"Phòng ban nhận"},
    {key:"DocumentNeedToBeExploited", value:"Văn bản cần khai thác"},
    {key:"SignToAcknowledge", value:"Ký nhận"},
    {key:"Are you sure you want to sign acknowledge?", value:"Bạn có chắc chắn muốn thực hiện ký?"},
    {key:"SignedToAcknowledge", value:"Đã ký nhận"},
    {key:"InputTitle", value:"Nhập tiêu đề"},
    {key:"InputAuthor", value:"Nhập tác giả"},
    {key:"InputNote", value:"Nhập ghi chú"},
    {key:"NumberCodeDocument", value:"Số, ký hiệu văn bản"},
    {key:"DateDocument", value:"Ngày tháng văn bản"},
    {key:"TypeDocumentAndExcerpt", value:"Tên loại và trích yếu nội dung văn bản"},
    {key:"ReceivingDocumentDepartment", value:"Nơi nhận văn bản"},
    {key:"OutgoingDocuments", value:"File văn bản đi"},
    {key:"AttachDocuments", value:"File đính kèm"},
    {key:"StorageName", value:"Tên kho lưu trữ"},
    {key:"StorageLocation", value:"Vị trí trong kho"},
    {key:"StorageType", value:"Loại kho"},
    {key:"RelatedInformation", value:"Thông tin liên quan"},
    {key:"TypeName", value:"Tên loại"},
    {key:"DocumentQuantity", value:"Số lượng văn bản"},
    {key:"TransferDate", value:"Ngày chuyển"},
    {key:"InvalidAction", value:"Hành động không hợp lệ"},
    {key:"ReceiverOrDepartmentNotificationIsRequired", value:"Người nhận hoặc phòng ban nhận cần được chọn"},
    {key:"InputQuantity", value:"Nhập số lượng"},
    {key:"PageNotFoundLine1", value:"Trang không tồn tại"},
    {key:"PageNotFoundLine2", value:"Trang bạn đang tìm kiếm không tồn tại hoặc bạn không có quyền truy cập vào trang này. Vui lòng liên hệ với quản trị viên để được hỗ trợ thêm."},
    {key:"NoPermissionLine1", value:"Truy cập bị từ chối"},
    {key:"NoPermissionLine2", value:"Xin lỗi, bạn không có quyền truy cập vào trang này. Vui lòng kiểm tra lại quyền truy cập hoặc liên hệ với quản trị viên để được hỗ trợ thêm."},
    {key:"CanNotAssignMultipleMainPerson", value:"Chỉ được phép giao một người chủ trì"},
    {key:"MainPersonRequired", value:"Người chủ trì không được để trống"},
    {key:"Input quantity", value:"Nhập số lượng"},
    {key:"DoYouWantReleaseODB", value:"Bạn có muốn phát hành sổ công văn đi không?"},
    {key:"ArrivedDate", value:"Ngày đến"},
    {key:"ReceivingUnit", value:"Đơn vị nhận"},
    {key:"BriefCase",value:"Hồ sơ"},
    {key:"NumberOfArrivedBook",value: "Số công văn đến"},
    {key:"OutgoingReferenceNumber",value: "Số công văn đi"},
    {key:"functionApply",value: "Chức năng áp dụng"},
    {key:"chooseColor",value: "Chọn Màu"},
    {key:"Fixed",value: "Cố định"},
    {key:"Flexible",value: "Linh hoạt"},
    {key:"Flexible",value: "Linh hoạt"},
    {key:"Handling methods",value: "Phương pháp xử lý"},
    {key:"Select an Option",value: "Chọn một lựa chọn"},
    {key:"Received",value:"Đã nhận"},
    {key:"TransactionNotificationReceived",value:"Đã nhận thông báo xử lý nghiệp vụ"},
    {key:"Automaticallycompletethetask",value:"Tự động kết thúc công việc"},
    {key:"ArchiveProfileComplete",value:"Hoàn thành hồ sơ lưu trữ"},
    {key:"task",value:"Công việc"},
    {key:"dispatch_arrived",value:"Công văn đến"},
    {key:"workflow_play",value:"Trình ký"},
    { key: "IsRepetitiveTask", value: "Là công việc lặp lại" },
    {key:"SendTo",value:"Gửi đến"},
    {key:"GeneralInformation",value:"Thông tin chung"},
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    {key:"NeedToHandleLevel_1",value:"Lãnh đạo cần xử lý"},
    {key:"NeedToHandleLevel_2",value:"Trưởng bộ phận cần xử lý"},
    {key:"Scope",value:"Phạm vi"},
    {key:"External",value:"Ngoài đơn vị"},
    {key:"Internal",value:"Nội bộ"},
    {key:"InputReason", value:"Nhập lý do"},
    {key:"RecallReason", value:"Lý do thu hồi"},
    // OCR
    {key:"Modification Action", value:"Chọn Hành Động Sửa Đổi"},
    {key:"Add Row/Column", value:"Thêm Hàng/Cột"},
    {key:"Remove Row/Column", value:"Xóa Hàng/Cột"},
    {key:"Apply Regex", value:"Áp Dụng Regex"},
    {key:"Split by Regex", value:"Tách Bằng Regex"},
    {key:"Merge tables", value:"Gộp bảng"},
    {key:"Split tables", value:"Chia bảng"},
    {key:"Arithmetic", value:"Tính Toán"},
    {key:"Merge", value:"Gộp Ô"},
    {key:"Copy", value:"Sao Chép"},
    {key:"Add Type", value:"Thêm loại"},
    {key:"Remove Type", value:"Thêm loại"},
    {key:"Row Values (comma-separated)", value:"Giá trị Hàng (cách nhau bằng dấu phẩy)"},
    {key:"Value1, Value2, ...", value:"Giá trị1, Giá trị2, ..."},
    {key:"Row Position", value:"Vị Trí Hàng"},
    {key:"Enter row position (0 for top)", value:"Nhập vị trí hàng (0 là đầu tiên)"},
    {key:"Column Default Value", value:"Giá Trị Mặc Định Của Cột"},
    {key:"Default value for column", value:"Giá trị mặc định cho cột"},
    {key:"Column Position", value:"Vị Trí Cột"},
    {key:"Enter column position (0 for leftmost)", value:"Nhập vị trí cột (0 là cột ngoài cùng bên trái)"},
    {key:"Row Indices to Remove (comma-separated)", value:"Chỉ mục hàng cần xóa (phân tách bằng dấu phẩy)"},
    {key:"Column Index to Remove", value:"Chỉ mục cột cần xóa"},
    {key:"Cell Coordinates (Row,Column)", value:"Tọa độ ô (Hàng,Cột)"},
    {key:"New Cell Value", value:"Giá trị ô mới"},
    {key:"Enter new value", value:"Nhập giá trị mới"},
    {key:"Arithmetic Operation", value:"Phép Toán Số Học"},
    {key:"Addition (+)", value:"Cộng (+)"},
    {key:"Subtraction (-)", value:"Trừ (-)"},
    {key:"Multiplication (*)", value:"Nhân (*)"},
    {key:"Division (/)", value:"Chia (/)"}, 
    {key:"Choose the operation to perform between the specified indices.", value:"Chọn phép toán để thực hiện giữa các chỉ số đã chỉ định."},
    {key:"Operation Type", value:"Loại Phép Toán"},
    {key:"Specify whether the operation applies to rows or columns.", value:"Chỉ định phép toán áp dụng cho hàng hay cột."},
    {key:"Index A", value:"Chỉ Số A"},
    {key:"Enter Index A (starting from 0)", value:"Nhập Chỉ Số A (bắt đầu từ 0)"},
    {key:"Example: 0 (Index for the first row/column for the operation).", value:"Ví dụ: 0 (Chỉ số cho hàng/cột đầu tiên của phép toán)."},
    {key:"Index B", value:"Chỉ Số B"},
    {key:"Enter Index B (starting from 0)", value:"Nhập Chỉ Số B (bắt đầu từ 0)"},
    {key:"Example: 1 (Index for the second row/column for the operation).", value:"Ví dụ: 1 (Chỉ số cho hàng/cột thứ hai của phép toán)."},
    {key:"Target Index", value:"Chỉ Số Mục Tiêu"},
    {key:"Enter Target Index (starting from 0)", value:"Nhập Chỉ Số Mục Tiêu (bắt đầu từ 0)"},
    {key:"Example: 2 (Index where the result will be stored).", value:"Ví dụ: 2 (Chỉ số nơi kết quả sẽ được lưu)."},
    {key:"Select a Popular Regex Pattern", value:"Chọn Mẫu Regex Phổ Biến"},
    {key:"-- Select a regex pattern --", value:"-- Chọn một mẫu regex --"},
    {key:"Or Enter Custom Regex", value:"Hoặc Nhập Regex Tùy Chỉnh"},
    {key:"Enter regex pattern", value:"Nhập mẫu regex"},
    {key:"Column Index", value:"Chỉ Số Cột"},
    {key:"Index of column to apply regex", value:"Chỉ số cột để áp dụng regex"},
    {key:"Enable Filter Mode", value:"Kích Hoạt Chế Độ Lọc"},
    {key:"Column Index", value:"Chỉ Số Cột"},
    {key:"Enter column index", value:"Nhập chỉ số cột"},
    {key:"Regex", value:"Regex"},
    {key:"Split Mode", value:"Chế Độ Tách"},
    {key:"Split into Columns", value:"Tách thành Cột"},
    {key:"Split by rows with missing data", value:"Tách bảng theo hàng thiếu dữ liệu"},
    {key:"Split into Rows", value:"Tách thành Hàng"},
    {key:"Separator (Optional)", value:"Dấu phân cách (Tùy chọn)"},
    {key:"Enter separator", value:"Nhập dấu phân cách"},
    {key:"Start Cell:", value:"Ô Bắt Đầu:"},
    {key:"End Cell:", value:"Ô Kết Thúc:"},
    {key:"Copy Mode", value:"Chế Độ Sao Chép"},
    {key:"Column to column", value:"Cột sang cột"},
    {key:"Row to row", value:"Hàng sang hàng"},
    {key:"Index:", value:"Chỉ Số:"},
    {key:"Target", value:"Mục Tiêu"},
    {key:"Paste To", value:"Dán Vào"},
    {key:"Add Modification", value:"Thêm Sửa Đổi"},
    {key:"Current Modifications", value:"Các Sửa Đổi Hiện Tại"},
    {key:"Note:", value:"Lưu Ý:"},
    {key:"Modifications will be executed from top to bottom. You can reorder them to change the execution sequence.", value:"Các sửa đổi sẽ được thực thi từ trên xuống dưới. Bạn có thể sắp xếp lại thứ tự để thay đổi trình tự thực thi."},
    {key:"Action", value:"Hành Động"},
    {key:"Details", value:"Chi Tiết"},
    {key:"Index", value:"Chỉ Số"},
    {key:"Filter", value:"Lọc"},
    {key:"Column", value:"Cột"},
    {key:"Row", value:"Hàng"},
    {key:"Actions", value:"Hành Động"},
    {key:"Cancel", value:"Hủy"},
    {key:"Save Changes", value:"Lưu Thay Đổi"},
    {key:"Apply Modification for Test", value:"Áp Dụng Sửa Đổi để Kiểm Tra"},
    {key:"Manage Modifications", value:"Quản lý sửa đổi"},
    {key:"From Date must be less than To Date", value:"Ngày bắt đầu phải nhỏ hơn ngày kết thúc"},
    {key:"Please select the document to export", value:"Vui lòng chọn tài liệu để xuất"},
    {key:"Document Data Preview", value:"Xem trước dữ liệu tài liệu"},

    

    {key:"InsertBundleErrorMessage", value:"Đã có lỗi xảy ra khi tạo mới bundle!"},
    {key:"Are you sure you want to delete this bundle?", value: "Bạn có chắc chắn muốn xóa bundle này không?"},
    {key:"DeleteBundleErrorMessage", value:"Đã có lỗi xảy ra khi xóa bundle!"},
    {key:"Create New Document Type", value: "Tạo mới loại tài liệu"},
    {key:"Visible Items", value: "Hiển thị"},
    {key:"DocumentTypeName", value: "Tên loại tài liệu"},
    {key:"DocumentTypeDescription", value:"Mô tả loại tài liệu"},
    {key:"Upload Documents", value:"Tải lên tài liệu"},
    {key:"Number of Documents", value:"Số lượng tài liệu"},
    {key:"Document Name", value:"Tên tài liệu"},
    {key:"ScanDocument", value:"Quét tài liệu đã chọn"},
    {key:"ScanStatus", value:"Trạng thái quét tài liệu"},
    {key: "OCR Template Note", value: "Đối với mỗi loại tài liệu, vui lòng tải lên một mẫu và định nghĩa các quy tắc cho nó. Khi một mẫu và các quy tắc của nó được thiết lập, bất kỳ tài liệu nào được tải lên thêm trong loại tài liệu này sẽ tự động kế thừa các quy tắc mẫu này làm mặc định." },
    {key:"You can modify rules for each individual document later if needed.", value:"Bạn có thể chỉnh sửa các quy tắc cho từng tài liệu riêng lẻ sau nếu cần."},
    {key:"Processed",value:"Đã xử lý"},
    {key:"Not Processed", value:"Chưa xử lý"},
    {key:"Extract Status", value:"Trạng thái trích xuất"},
    {key:"Extracted Data", value:"Dữ liệu trích xuất"},
    {key:"Extracted Data From Template", value:"Dữ liệu trích xuất từ file mẫu"},
    {key:"Field Name", value:"Tên trường"},
    {key:"Coordinates", value:"Tọa độ"},
    {key:"Upload Template", value:"Tải lên tệp tin mẫu"},
    {key:"Zoom", value:"Thu Phóng"},
    {key:"Zoom In", value:"Phóng to"},
    {key:"Zoom Out", value:"Thu nhỏ"},
    {key:"Real Size", value:"Kích thước thực tế"},
    {key:"Enter field name", value:"Nhập vào tên trường"},
    {key:"Page", value:"Trang"},
    {key:"Add Rule", value:"Thêm quy tắc"},
    {key:"Post-Process", value:"Xử lý"},
    {key:"Saving...", value:"Đang lưu..."},
    {key:"Loading...", value:"Đang tải..."},
    {key:"Verify Rule on Template", value:"Xác minh quy tắc trên mẫu"},
    {key:"Verifying...", value:"Đang xác minh..."},
    {key:"Hide Grid", value:"Ẩn lưới"},
    {key:"Show Grid", value:"Hiển thị lưới"},
    {key:"Hide Details", value:"Ẩn chi tiết"},
    {key:"Show Details", value:"Hiển thị chi tiết"},
    {key:"Hide Document Content", value:"Ẩn nội dung tài liệu"},
    {key:"Show Document Content", value:"Hiển thị nội dung tài liệu"},
    {key:"You have unsaved changes. Please save your work.", value:"Bạn chưa lưu thay đổi. Vui lòng lưu công việc của bạn."},
    {key:"Upload Document",value:"Tạo mới tài liệu"},
    {key:"Ensure that all rules in the popup window are defined correctly. Remember to save your rules before leaving this page or when you're confident the rules work correctly for the template.",value:"Đảm bảo rằng tất cả các quy tắc trong cửa sổ bật lên được định nghĩa chính xác. Hãy nhớ lưu các quy tắc của bạn trước khi rời khỏi trang này hoặc khi bạn tin chắc rằng các quy tắc hoạt động chính xác cho mẫu."},
    {key:"When you upload a testing file, the system will automatically run OCR on the uploaded document using the temporary rules defined in the popup window to verify their accuracy.",value:"Khi bạn tải lên tệp thử nghiệm, hệ thống sẽ tự động chạy OCR trên tài liệu đã tải lên bằng cách sử dụng các quy tắc tạm thời được xác định trong cửa sổ bật lên để xác minh độ chính xác của chúng."},
    {key:"Are you sure you want to delete this document?",value:"Bạn có chắc chắn muốn xóa tài liệu này?"},
    {key:"Upload Testing Files",value:"Tải lên tập tin thử nghiệm"},
    {key:"Delete Document",value:"Xoá tài liệu"},
    {key:"Table Data and Modifications",value:"Bảng dữ liệu và sửa đổi"},
    {key:"Raw Table Data",value:"Dữ liệu bảng"},
    {key:"Post-Processed Table Data",value:"Dữ liệu bảng sau khi xử lý"},
    {key:"No post-processed table data available. Apply modifications to generate.",value:"Không có dữ liệu bảng sau khi xử lý. Áp dụng các sửa đổi để tạo."},


    {key:"No Document Type found",value:"Không tìm thấy loại tài liệu"},
    {key:"Display",value:"Hiển thị"},
    {key:"Uploading template...", value:"Tải lên tệp tin mẫu..."},
    {key:"Note: When uploading a test file, the system will automatically use the temporary rules in the popup to verify the accuracy of the uploaded document. Make sure to save the rules before leaving the page or when you're confident they work correctly.", value:"Ghi chú: Khi tải lên tệp thử nghiệm, hệ thống sẽ tự động sử dụng các quy tắc tạm thời trong cửa sổ bật lên để kiểm tra độ chính xác của tài liệu đã tải. Hãy đảm bảo lưu các quy tắc trước khi rời khỏi trang hoặc khi bạn chắc chắn chúng hoạt động chính xác."},
    {key:"Use AI for Processing", value:"Sử dụng AI để trích xuất"}
];
