module.exports =[
    {key:"UnionChairman",value:"Chủ tịch công đoàn"},
    {key:"HospitalChiefNursing",value:"Điều dưỡng Trưởng bệnh viện"},
    {key:"DepartmentChiefNursing",value:"Điều dưỡng Trưởng khoa"},
    {key:"UnionMembers",value:"Đoàn viên"},
    {key:"Director",value:"Giám đốc"},
    {key:"ChiefMidwives",value:"Hộ sinh trưởng"},
    {key:"Apprentice",value:"Học việc"},
    {key:"Chiefaccountant",value:"Kế toán trưởng"},
    {key:"Other",value:"Khác"},
    {key:"ChiefTechnician",value:"Kỹ thuật viên trưởng"},
    {key:"Employee",value:"Nhân viên"},
    {key:"ViceDirector",value:"Phó Giám đốc"},
    {key:"DeputyChiefOfDepartment",value:"Phó trưởng bộ phận"},
    {key:"DeputyHeadOfOffice",value:"Phó Trưởng phòng"},
    {key:"Storekeeper",value:"Thủ kho"},
    {key:"Secterary",value:"Thư ký"},
    {key:"ViceTeamLeader",value:"Tổ phó"},
    {key:"Leader",value:"Tổ trưởng"},
    {key:"UnionLeader",value:"Tổ trưởng công đoàn"},
    {key:"ChiefOfDepartment",value:"Trưởng bộ phận"},
    {key:"HeadOfDepartment",value:"Trưởng phòng"}    
];