module.exports =[
    {key:"HRM",value:"HRM"},
    {key:"ResumesManagement",value:"Resumes Management"},
    {key:"GroupManagement",value:"Group management"},
    {key:"DepartmentGroupManagement",value:"Department Group management"},
    {key:"MenuManagement",value:"Menu management"},
    {key:"QuickIconManagement",value:"Quick Icon management"},
    {key:"OrganizationManagement",value:"Organization Management"},
    {key:"TechniqueList",value:"Technique List"},
    {key:"RoleManagement",value:"Role management"},
    {key:"RuleManagement",value:"Rule management"},
    {key:"UserManagement",value:"User management"},
    {key:"ManagementEmployee",value:"Administration"},
    {key:"TechniqueList",value:"Technique List"},
    {key:"RecycleBinManagement",value:"RecycleBin"},
    {key:"features",value:"Features"},
    {key:"InputKeyOfGroupGenu",value:"input key of group menu"},
    {key:"InputIconOfGroupMenu",value:"input icon of group menu"},
    {key:"notify",value:"Notify"},
    {key:"UpdateMenu",value:"Update Menu"},
    {key:"Setting",value:"Setting"},
    {key:"LaborContractDetails",value:"Labor contract details"},
    {key:"NotifyDetails",value:"Notify details"},
    {key:"SignDetails",value:"Sign details"},
    {key:"LeaveFormDetails",value:"Leave form details"},
    {key:"TaskDetails",value:"Task details"},
    {key:"WikiDetails",value:"Wiki details"},
    {key:"DADetails",value:"Dispatch arrived details"},
    {key:"JourneyTimeDetails",value:"Journey time details"},
    {key:"TaskWorkflow",value:"Task workflow management"},
    {key:"File",value:"File management"},
    {key:"StudyPlan",value:"Study Plan"},
    {key:"ExamSchedule",value:"Exam Schedule"},
    {key:"PDFToExcel",value:"PDF To Excel"},
    {key:"CalculateDimensions",value:"Calculate Dimensions"},
    {key:"Storage",value:"Storage"},
    {key:"SendingPlace",value:"Sending Place"},
    {key:"WaitingStorage",value:"Waiting Storage"},
    {key:"RecordAccess",value:"Record Access"},
    {key:"File",value:"File management"},
    {key:"QuestionAnswer",value:"Question Answer"},
    {key:"TrainingPoint",value:"Training Point"},
    {key:"AdministrativeProcedures",value:"Administrative procedures"},
    {key:"MeetingRoom",value:"Meeting room"},
    {key:"MeetingRoomScheduleConferenceRoom",value:"Meeting Room Schedule - Conference Room"},
    {key:"Today",value:"Today"},
    // Date of week
    {key:"Monday", value: "Monday"},
    {key:"Tuesday", value: "Tuesday"},
    {key:"Wednesday", value: "Wednesday"},
    {key:"Thursday", value: "Thurday"},
    {key:"Friday", value: "Friday"},
    {key:"Saturday", value: "Saturday"},
    {key:"Sunday", value: "Sunday"},
    // Status meeting room
    {key:"Registered", value: "Registered"},
    {key:"Approved", value: "Approved"},
    {key:"RequestCancel", value: "Request Cancel"},
    {key:"Cancelled", value: "Cancelled"},
    {key:"Rejected", value: "Rejected"},
    {key: "Confirmed", value: "Confirmed"},
    // Title header update meeting room
    {key: "RoomRegistrationUpdate", value: "Room Registration Update"},
    {key: "Room", value: "Room"},
    {key: "SelectRoom", value: "Select Room"},
    {key: "ExportToExcel", value: "Export to excel"},
];
