module.exports =[
    {key:"HRM",value:"Quản lý nhân sự"},
    {key:"ResumesManagement",value:"Sơ yếu lý lịch"},
    {key:"GroupManagement",value:"Quản lý nhóm"},
    {key:"DepartmentGroupManagement",value:"Quản lý nhóm phòng ban"},
    {key:"MenuManagement",value:"Quản lý menu"},
    {key:"QuickIconManagement",value:"Quản lý tiện ích nhanh"},
    {key:"RoleManagement",value:"Quản lý vai trò"},
    {key:"RuleManagement",value:"Quản lý quyền"},
    {key:"UserManagement",value:"Quản lý tài khoản"},
    {key:"ManagementEmployee",value:"Quản lý"},
    {key:"OrganizationManagement",value:"Damh mục phòng ban"},
    {key:"TechniqueList",value:"Danh mục chuyên môn"},
    {key:"RecycleBinManagement",value:"Thùng rác"},
    {key:"features",value:"Tính năng"},
    {key:"InputKeyOfGroupGenu",value:"Nhập từ khóa nhóm menu"},
    {key:"InputIconOfGroupMenu",value:"Nhập icon của nhóm menu"},
    {key:"notify",value:"Bản tin"},
    {key:"UpdateMenu",value:"Cập nhật Menu"},
    {key:"Setting",value:"Thiết đặt"},
    {key:"LaborContractDetails",value:"Chi tiết hợp đồng lao đồng"},
    {key:"NotifyDetails",value:"Chi tiết thông báo"},
    {key:"SignDetails",value:"Chi tiết trình ký"},
    {key:"LeaveFormDetails",value:"Chi tiết đơn nghỉ phép"},
    {key:"TaskDetails",value:"Chi tiết công việc"},
    {key:"WikiDetails",value:"Chi tiết Wiki"},
    {key:"DADetails",value:"Chi tiết công văn đến"},
    {key:"JourneyTimeDetails",value:"Chi tiết giấy đi đường"},
    {key:"TaskWorkflow",value:"Quản lý workflow công việc"},
    {key:"File",value:"Quản lý tài liệu"},
    {key:"StudyPlan",value:"Quản lý lịch học"},
    {key:"ExamSchedule",value:"Quản lý lịch thi"},
    {key:"PDFToExcel",value:"Chuyển PDF sang Excel"},
    {key:"CalculateDimensions",value:"Tính toán kích thước"},
    {key:"File",value:"Quản lý tài liệu"},
    {key:"QuestionAnswer",value:"Hỏi đáp"},
    {key:"TrainingPoint",value:"Điểm rèn luyện"},
    {key:"Storage",value:"Lưu trữ"},
    {key:"SendingPlace",value:"Nơi gửi văn bản"},
    {key:"WaitingStorage",value:"Chờ Lưu trữ"},
    {key:"RecordAccess",value:"Khai thác hồ sơ"},
    {key:"AdministrativeProcedures",value:"Thủ tục hành chính"},
    {key:"MeetingRoom",value:"Phòng họp"},
    {key:"MeetingRoomScheduleConferenceRoom",value:"Lịch Hội Trường - Phòng Họp"},
    {key:"Today",value:"Hôm nay"},
    // Date of week
    {key:"Monday", value: "Thứ Hai"},
    {key:"Tuesday", value: "Thứ ba"},
    {key:"Wednesday", value: "Thứ Tư"},
    {key:"Thursday", value: "Thứ Năm"},
    {key:"Friday", value: "Thứ Sáu"},
    {key:"Saturday", value: "Thứ Bảy"},
    {key:"Sunday", value: "Chủ nhật"},
    // Status meeting room
    {key:"Registered", value: "Đã đăng ký"},
    {key:"Approved", value: "Đã duyệt"},
    {key:"RequestCancel", value: "Yêu cầu hủy"},
    {key:"Cancelled", value: "Đã hủy"},
    {key:"Rejected", value: "Từ chối"},
    {key: "Confirmed", value: "Đã xác nhận"},
    // Title header update meeting room
    {key: "RoomRegistrationUpdate", value: "Cập nhật đăng ký phòng họp"},
    {key: "Room", value: "Phòng"},
    {key: "SelectRoom", value: "Chọn phòng"},
    {key: "ExportToExcel", value: "Xuất file"},
];
