module.exports =[
    {key:"BoardOfDirector",value:"Board Of Director"},
{key:"MarketingUnit",value:"Marketing unit"},
{key:"CosmeticSurgeryUnit",value:"Cosmetic Surgery unit"},
{key:"EmergencyDepartment",value:"Emergency Department"},
{key:"DiagnosticImagingDepartment",value:"Diagnostic Imaging Department"},
{key:"DermatologyDept",value:"Dermatology Dept."},
{key:"NutritionDepartment",value:"Nutrition Department"},
{key:"PharmacyDepartment",value:"Pharmacy Department"},
{key:"PathologyDepartment",value:"Pathology Department"},
{key:"BiochemistryDepartment",value:"Biochemistry Department"},
{key:"PediatricIntensiveCareAndToxicManagementDepartmentB",value:"Pediatric Intensive Care And Toxic Management Department B"},
{key:"HematologyDept",value:"Hematology Dept."},
{key:"OutpatientDepartment",value:"Outpatient Department"},
{key:"InfectionControl Dept",value:"Infection Control Dept."},
{key:"OphthalmologyDept",value:"Ophthalmology Dept."},
{key:"ThoracicSurgeryDept",value:"Thoracic surgery Dept"},
{key:"NeurosurgeryDepartment",value:"Neurosurgery Department"},
{key:"PediatricsDept",value:"Pediatrics Dept."},
{key:"NeurologyDept",value:"Neurology Dept."},
{key:"EndocrinologyDept",value:"Endocrinology Dept"},
{key:"GeneralPediatricDepartment",value:"General Pediatric Department"},
{key:"DepartmentOfAnaesthesiaAndIntensiveCare",value:"Department Of Anaesthesia And Intensive Care"},
{key:"MaternityUnit",value:"Maternity Unit"},
{key:"EarNoseThroatDept",value:"Ear – Nose -Throat Dept."},
{key:"PsychologyDepartment",value:"Psychology Department"},
{key:"NeurologyDepartment",value:"Neurology Department"},
{key:"UrologyDept",value:"Urology Dept."},
{key:"InterventionalCardiologyDept.",value:"Interventional Cardiology Dept."},
{key:"PhysicalTherapyDept",value:"Physical therapy Dept."},
{key:"MicrobiologyDepartment",value:"Microbiology Department"},
{key:"MedicalInsuranceUnit",value:"Medical Insurance unit"},
{key:"CustomerCareDept",value:"Customer Care Dept."},
{key:"DepartmentOfHealthActivitiesDirection",value:"Department Of Health Activities Direction"},
{key:"InformationTechnololyDept",value:"Information Technololy Dept."},
{key:"NursingDepartment",value:"Nursing Department"},
{key:"GeneralPlanningDepartment",value:"General Planning Department"},
{key:"AccountingDept",value:"Accounting Dept."},
{key:"QualityManagementDepartment",value:"Quality Management Department"},
{key:"HumanResourceDepartment",value:"Human Resource Department"},
{key:"DepartmentOfMedicalEquipmentMaterial",value:"Department Of Medical Equipment & Material"},
{key:"StaffHealthcareDept",value:"Staff Healthcare Dept."}
   
];