module.exports =[
    {key:"Notify",value:"Notify"},
    { key: "NewNotify", value: "New Notify" },
    {key:"EditNotify",value:"Edit Notify"},
    {key:"NoAttachment",value:"NoAttachment"},
    {key:"Private",value:"Private"},
    {key:"Public",value:"Public"},
    {key:"Person",value:"Person"},
    {key:"Content",value:"Content"},
    {key:"PolicyRegime",value:"Policy regime"},
    {key:"DispatchArrived",value:"Dispatch arrived"},
    {key:"DispatchAway",value:"Dispatch away"},
    {key:"SeparateDispatch",value:"Separate dispatch"},
    {key:"CompetitionConferenceSportsFestival",value:"Competition, conference, sports festival"},
    {key:"Other",value:"Other"},
    {key:"Urgent",value:"Urgent"},
    {key:"Holidays",value:"Holidays"},
    {key:"Remind",value:"Remind"},
    {key:"Training",value:"Training"},
    {key:"StartThePlan",value:"Start the plan"},
    {key:"DocumentForSignature",value:"Document for signature"},
    {key:"To",value:"To"},
    {key:"From",value:"From"},
    {key:"NotifyUnSubscribe",value:"Notify UnSubscribe"},
    {key:"NotifyNew",value:"Notify New"},
    {key:"NotifyGroupManagement",value:"Notify Group Management"},
    {key:"NotifyWaitingForApproval",value:"Notify Waiting For Approval"},
    {key:"NotifySent",value:"Notify Sent"},
    {key:"NotifyReceived",value:"Notify Received"},
    {key:"TechniqueList",value:"Technique List"},
    {key:"Attachment",value:"Attachment"},
    {key:"UNSUBCRIBE",value:"Unsubscribe"},
    { key:"Cancelled", value: "Cancelled" },
    {key:"Employees",value:"Employees"},
    {key:"CurrentTask", value:"Current Task"},
    {key:"CompletedTask", value:"Completed Task"},
    {key:"Overdue",value:"Overdue"},
    {key:"GonnaLate",value:"Approaching deadline"},
    {key:"Open",value:"Open"},
    {key:"AddTaskForThis",value:"Add New Task"},
    {key:"AddFile",value:"Add file"},
    {key:"PickPerson",value:"Pick person"},
    {key:"ViewTaskDetail",value:"View task detail"},
    {key:"KeepAddingTask",value:"Keep adding task"},
    {key:"AssignedToYourDepartment",value:"Assigned to your department"},
    {key:"Approve Recall",value:"Approve Recall"}
];
