module.exports =[
    {key:"Notify",value:"Bản tin"},
    {key:"NewNotify",value:"Thông báo mới"},
    {key:"EditNotify",value:"Cập nhập thông báo"},
    {key:"Content",value:"Nội dung"},
    {key:"Private",value:"Riêng tư"},
    {key:"Private",value:"Riêng tư"},
    {key:"Public",value:"Cộng đồng"},
    {key:"Person",value:"Cá nhân"},
    {key:"NoAttachment",value:"Không có tập tin đính kèm"},
    {key:"PolicyRegime",value:"Chế độ chính sách"},
    {key:"DispatchArrived",value:"Công văn đến"},
    {key:"DispatchAway",value:"Công văn đi"},
    {key:"SeparateDispatch",value:"Công văn riêng biệt"},
    {key:"CompetitionConferenceSportsFestival",value:"Hội thi, hội diễn, hội thao"},
    {key:"Other",value:"Khác"},
    {key:"Urgent",value:"Khẩn"},
    {key:"Holidays",value:"Nghỉ lễ"},
    {key:"Remind",value:"Nhắc nhở"},
    {key:"Training",value:"Tập huấn"},
    {key:"StartThePlan",value:"Triển khai kế hoạch "},
    {key:"DocumentForSignature",value:"Văn bản trình ký"},
    {key:"To",value:"Đến"},
    {key:"From",value:"Từ"},
    {key:"NotifyUnSubscribe",value:"Ngừng theo dõi"},
    {key:"NotifyNew",value:"Tạo mới"},
    {key:"NotifyGroupManagement",value:"Nhóm thông báo"},
    {key:"NotifyWaitingForApproval",value:"Chờ phê duyệt"},
    {key:"NotifyReceived",value:"Đã nhận"},
    {key:"TechniqueList",value:"Danh mục chuyên môn"},
    {key:"NotifySent",value:"Đã gửi"},
    {key:"Attachment",value:"Tệp đính kèm"},
    {key:"UNSUBCRIBE",value:"Ngừng theo dõi"},
    {key:"Cancelled",value:"Đã huỷ bỏ"},
    {key:"Employees",value:"Nhân viên"},
    {key:"CurrentTask", value:"Công việc hiện tại"},
    {key:"CompletedTask", value:"Công việc hoàn thành"},
    {key:"Overdue",value:"Quá hạn"},
    {key:"GonnaLate",value:"Sắp trễ hạn"},
    {key:"Open",value:"Còn hạn"},
    {key:"AddTaskForThis",value:"Thêm công việc mới"},
    {key:"AddFile",value:"Thêm tập tin"},
    {key:"PickPerson",value:"Chọn người"},
    {key:"ViewTaskDetail",value:"Xem chi tiết công việc"},
    {key:"KeepAddingTask",value:"Tiếp tục thêm công việc"},
    {key:"AssignedToYourDepartment",value:"Đã giao cho phòng ban của bạn"},
    {key:"Approve Recall",value:"Phê duyệt thu hồi"}
];
