module.exports=[
    // key hệ thống
    {key:"There are some notices that require your approval",value:"There are {{count}} notices that require your approval"},
    {key:"You have not read some notifications",value:"You have not read {{count}} notifications"},
    {key:"You have not completed some tasks",value:"You have not completed {{count}} tasks"},
    {key:"The some task you created have not been completed",value:"The {{count}} task you created have not been completed"},
    {key:"There are some incoming dispatch documents that need to be processed",value:"There are {{count}} incoming dispatch documents that need to be processed"},
    {key:"There are some documents requesting your approval",value:"There are {{count}} documents requesting your approval"},
    {key:"There are some leave requests that require your approval",value:"There are {{count}} leave requests that require your approval"},
    {key:"There are some requirements for journey time",value:"There are {{count}} requirements for journey time"},
    {key:"There are some labor contracts that require your approval",value:"There are {{some}} labor contracts that require your approval"},
    {key:"There is 1 new question created by a student",value:"There is 1 new question created by a student {{studentName}}"},
    {key:"There is a forwarded question from",value:"There is a forwarded question from {{employeeName}}"},
    {key:"Questions are answered by students",value:"Questions {{subject}} are answered by {{studentName}}"},
    {key:"Questions are closed by students",value:"Questions {{subject}} are closed by {{studentName}}"},
    {key:"LoadMore",value:"Load more"},
    {key:"just updated participants by",value:"just updated participants by"},
    {key:"just updated title by",value:"just updated title by"},
    {key:"just updated workflow play by",value:"just updated workflow play by"},
    {key:"just updated project implementation time by",value:"just updated project implementation time by"},
    {key:"just updated status to project",value:"just updated status to project"},
    {key:"just created project",value:"just created project"},
    {key:"just add proof to task",value:"just add proof to task {{title}}"},
    {key:"just remove proof from task",value:"just remove proof to task {{title}}"},
    {key:"was overdue from",value:"was overdue from"},
    {key:"You have number tasks with upcoming deadlines this week",value:"[Reminder] You have {{number}} tasks with upcoming deadlines this week:"},
    {key: "Task is due tomorrow",value:"[Reminder] {{title}} is due tomorrow."},
    {key: "WorkflowPlayExpireToday", value: "{{title}} has been overdue from {{from_date}} to {{to_date}}"},
    {key: "WorkflowPlayExpireSoon", value: "{{title}} will be overdue from {{from_date}} to {{to_date}}"},
    {key: "JustReleasedBy", value: "just released by"},
    {key:"ViewOlderAnnouncements",value: "View older announcements"},
    {key:"Need you to review and provide guidance",value: "Need you to review and provide guidance"},
    {key:"Need you to review and provide your opinion",value: "Need you to review and provide your opinion"},
    {key:"accept the processing of incoming official document",value: "accept the processing of incoming official document"},
    {key:"refuse the processing of incoming official document",value: "refuse the processing of incoming official document"},
    {key:"is assigned a task",value: "is assigned a task"},
    {key:"Need you to process",value: "Need you to process"},
    {key:"by",value: "by"},
    {key:"Need you to lead",value: "Need you to lead"},
    {key:"Need your coordination",value: "Need your coordination"},
    {key:"Need you to supervision",value: "Need you to supervision"},
    {key:"is updated signature link",value: "is updated signature link"},
    {key:"is updated signature link by",value: "is updated signature link by"},
    {key:"is updated participants",value: "is updated participants"},
    {key:"is updated title to",value: "is updated title to"},
    {key:"updated title to",value: "updated title to"},
    {key:"is updated time",value: "is updated time"},
    {key:"updated time",value: "updated time"},
    {key:"added comment to task",value: "added comment to task"},
    {key:"started task",value: "started task"},
    {key:"done task",value: "done task"},
    {key:"marked to completed task",value: "marked to completed task"},
    {key:"cancel task",value: "cancel task"},
    {key:"added proof to task",value: "added proof to task"},
    {key:"removed proof from task",value: "removed proof from task"},
    {key:"pushed file",value: "pushed file"},
    {key:"to task",value: "to task"},
    {key:"removed file",value: "removed file"},
    {key:"from task",value: "from task"},
    {key:"is updated progress from",value: "is updated progress from"},
    {key:"updated progress from",value: "updated progress from"},
    {key:"to progress",value: "to"},
    {key:"is updated information",value: "is updated information"},
    {key:"updated information",value: "updated information"},
    {key:"Need you to approve",value: "Need you to approve"},
    {key:"Need you to review and record it in the official document registry",value: "Need you to review and record it in the official document registry"},
    {key:"approved the signature",value: "approved the signature"},
    {key:"rejected the signature",value: "rejected the signature"},
    {key:"approved your signature",value: "approved your signature"},
    {key:"rejected your signature",value: "rejected your signature"},
    {key:"Signature WF",value: "Signature"},
    {key:"returned the signature",value: "returned the signature"},
    {key:"returned your signature",value: "returned your signature"},
    {key:"deleted the signature",value: "deleted the signature"},
    {key:"has been completed",value: "has been completed"},
    {key:"has forwarded",value: "has forwarded"},
    {key:"for signature by authority",value: "for signature by authority"},
    {key:"to",value: "to"},
    {key:"Not seen",value: "Not seen"},
    {key:"Mark as seen all",value: "Mark as seen all"},

    {key:"Need you to review and approve notify",value: "Need you to review and approve notify"},
    {key:"Need you to review and approve recall notify",value: "Need you to review and approve recall notify"},
    {key:"rejected the notify",value: "rejected the notify"},
    {key:"approved the notify", value: "approved the notify" },
    {key:"Department leader approved recall the notify",value: "approved recall the notify"},
    {key:"approved recall the notify",value: "approved recall the notify"},
    {key: "Department leader approved. Need you to review and approve notify", value: "Department leader approved. Need you to review and approve notify"},
    {key: "Department leader approved recall. Need you to review and approve notify", value: "Department leader approved recall. Need you to review and approve notify"},
    { key: "No more notify", value: "No more notify" },
    {key: "ManageNotify", value: "Manage notify"},
];
