module.exports=[
    {key:"There are some notices that require your approval",value:"Có {{count}} thông báo cần bạn phê duyệt"},
    {key:"You have not read some notifications",value:"Bạn chưa xem {{count}} thông báo"},
    {key:"You have not completed some tasks",value:"Bạn chưa hoàn thành {{count}} công việc được giao"},
    {key:"The some task you created have not been completed",value:"{{count}} công việc bạn đã tạo chưa được hoàn thành"},
    {key:"There are some incoming dispatch documents that need to be processed",value:"Có {{count}} công văn đến cần bạn xử trí"},
    {key:"There are some documents requesting your approval",value:"Có {{count}} văn bản cần bạn phê duyệt"},
    {key:"There are some leave requests that require your approval",value:"Có {{count}} đơn nghỉ phép cần bạn phê duyệt"},
    {key:"There are some requirements for journey time",value:"Có {{count}} yêu cầu cấp giấy đi đường"},
    {key:"There are some labor contracts that require your approval",value:"Có {{count}} hợp đồng lao động cần bạn phê duyệt"},
    {key:"There is 1 new question created by a student",value:"Có 1 câu hỏi mới được tạo bởi sinh viên {{studentName}}"},
    {key:"There is a forwarded question from",value:"Có 1 câu hỏi được chuyển tiếp từ {{employeeName}}"},
    {key:"Questions are answered by students",value:"Câu hỏi {{subject}} được sinh viên {{studentName}} trả lời"},
    {key:"Questions are closed by students",value:"Câu hỏi {{subject}} được sinh viên {{studentName}} đóng"},
    {key:"LoadMore",value:"Tải thêm"},
    {key:"just updated participants by",value:"vừa cập nhật người tham gia bởi"},
    {key:"just updated title by",value:"vừa cập nhật tiêu đề bởi"},
    {key:"just updated workflow play by",value:"vừa cập nhật liên kết trình ký bởi"},
    {key:"just updated project implementation time by",value:"vừa cập nhật thời gian thực hiện dự án bởi"},
    {key:"just updated status to project",value:"vừa cập nhật trạng thái dự án"},
    {key:"just created project",value:"vừa tạo mới dự án"},
    {key:"just add proof to task",value:"vừa thêm minh chứng hoàn thành cho công việc {{title}}"},
    {key:"just remove proof from task",value:"vừa xóa minhh chứng hoàn thành khỏi công việc {{title}}"},
    {key:"was overdue from",value:"đã bị trễ hạn từ"},
    {key:"You have number tasks with upcoming deadlines this week",value:"[Nhắc nhở] Bạn có {{number}} công việc sắp tới hạn trong tuần này:"},
    {key: "Task is due tomorrow",value:"[Nhắc nhở] {{title}} tới hạn vào ngày mai."},
    {key: "WorkflowPlayExpireToday", value: "{{title}} đã bị trễ hạn từ {{from_date}} đến {{to_date}}"},
    {key: "WorkflowPlayExpireSoon", value: "{{title}} sắp tới hạn từ {{from_date}} đến {{to_date}}"},
    {key: "JustReleasedBy", value: "vừa được phát hành bởi"},
    {key:"ViewOlderAnnouncements",value: "Xem các thông báo cũ hơn"},
    {key:"Need you to review and provide guidance",value: "Cần bạn xem qua và chỉ đạo"},
    {key:"Need you to review and provide your opinion",value: "Cần bạn xem qua và cho ý kiến"},
    {key:"accept the processing of incoming official document",value: "đồng ý xử lý công văn đến"},
    {key:"refuse the processing of incoming official document",value: "từ chối xử lý công văn đến"},
    {key:"is assigned a task",value: "được giao một công việc"},
    {key:"Need you to process",value: "Cần bạn xử lý"},
    {key:"You assigned task",value: "Bạn được giao công việc"},
    {key:"by",value: "bởi"},
    {key:"Need you to lead",value: "Cần bạn chủ trì"},
    {key:"Need your coordination",value: "Cần bạn phối hợp"},
    {key:"Need you to supervision",value: "Cần bạn giám sát"},
    {key:"is updated signature link",value: "đã được cập nhật liên kết trình ký"},
    {key:"is updated signature link by",value: "đã được cập nhật liên kết trình ký bởi"},
    {key:"is updated participants",value: "đã được cập nhật người tham gia"},
    {key:"is updated title to",value: "đã được cập nhật tiêu đề thành"},
    {key:"updated title to",value: "đã cập nhật tiêu đề thành"},
    {key:"is updated time",value: "đã được cập nhật thời gian"},
    {key:"updated time",value: "đã cập nhật thời gian"},
    {key:"added comment to task",value: "đã thêm bình luận cho công việc"},
    {key:"started task",value: "đã bắt đầu công việc"},
    {key:"done task",value: "đã làm xong công việc"},
    {key:"marked to completed task",value: "đã đánh dấu hoàn thành cho công việc"},
    {key:"cancel task",value: "đã hủy công việc"},
    {key:"added proof to task",value: "đã thêm minh chứng cho công việc"},
    {key:"removed proof from task",value: "đã xóa minh chứng khỏi công việc"},
    {key:"pushed file",value: "đã đính kèm tập tin"},
    {key:"to task",value: "vào công việc"},
    {key:"removed file",value: "đã xóa tập tin"},
    {key:"from task",value: "khỏi công việc"},
    {key:"is updated progress from",value: "đã được cập nhật tiến độ từ"},
    {key:"updated progress from",value: "đã cập nhật tiến độ từ"},
    {key:"to progress",value: "thành"},
    {key:"is updated information",value: "đã được cập nhật thông tin"},
    {key:"updated information",value: "đã cập nhật thông tin"},
    {key:"Need you to approve",value: "Cần bạn phê duyệt"},
    {key:"Need you to review and record it in the official document registry",value: "Cần bạn xem qua và lưu vào sổ công văn đi"},
    {key:"approved the signature",value: "đã phê duyệt trình ký"},
    {key:"rejected the signature",value: "đã bác bỏ trình ký"},
    {key:"approved your signature",value: "đã phê duyệt trình ký của bạn"},
    {key:"rejected your signature",value: "đã bác bỏ trình ký của bạn"},
    {key:"Signature WF",value: "Trình ký"},
    {key:"returned the signature",value: "đã trả lại trình ký"},
    {key:"returned your signature",value: "đã trả lại trình ký của bạn"},
    {key:"has been completed",value: "đã hoàn tất"},
    {key:"has forwarded",value: "đã chuyển"},
    {key:"for signature by authority",value: "để ký thừa lệnh"},
    {key:"to",value: "đến"},
    {key:"Not seen",value: "Chưa xem"},
    {key:"Mark as seen all",value: "Đánh dấu đã xem tất cả"},
    {key:"Need you to review and approve notify",value: "Cần bạn xem qua và duyệt bản tin"},
    {key:"Need you to review and approve recall notify",value: "Cần bạn xem qua và duyệt thu hồi bản tin"},
    {key:"rejected the notify",value: "đã bác bỏ bản tin"},
    {key:"approved the notify",value: "đã duyệt bản tin"},
    { key: "approved recall the notify", value: "đã duyệt thu hồi bản tin" },
    {key: "Department leader approved. Need you to review and approve notify", value: "Trưởng bộ phận đã duyệt. Cần bạn xem qua và duyệt bản tin"},
    {key: "Department leader approved. Need you to review and approve recall notify", value: "Trưởng bộ phận đã duyệt. Cần bạn xem qua và duyệt thu hồi bản tin"},
    {key: "No more notify", value: "Bản tin đã hết"},
    {key: "ManageNotify", value: "Quản lý bản tin"},

];
