module.exports=[
    // key hệ thống
    {key:"Login",value:"Login"},
    {key:"SignUp",value:"Sign up"},
    {key:"SignInToYourAccount",value:"Signin to your Account"},
    {key:"InvalidSigninInformation",value:"Invalid Signin Information!"},
    {key:"ForgotPassword",value:"Forgot Password"},
    {key:"UserName",value:"Username"},
    {key:"PassWord",value:"Password"},
    {key:"RememberMe",value:"Remember"},

    {key:"DoYouWantDelete",value: "Do you want delete {{title}}?"},
    {key:"DoYouWantApprove",value: "Do you want approve {{title}}?"},
    { key: "DoYouWantReject", value: "Do you want reject {{title}}?" },
    {key:"DoYouWantRecall",value: "Do you want recall {{title}}?"},
    {key:"DoYouWantResetPassword",value: "Do you want reset password for account: {{title}}?"},
    {key:"DoYouWantThrowToRecyclebin",value: "Do you want throw {{title}} to recyclebin?"},
    { key: "DoYouWantRestoreFromRecyclebin", value: "Do you want restore {{title}} from recyclebin?" },
    {key:"DoYouWantRejectNotify",value: "Do you want reject notify?"},
    {key:"HomePage",value:"Home Page"},
    {key:"Menu",value:"Menu"},
    {key:"Group",value:"Group"},
    {key:"DepartmentGroup",value:"Department Group"},
    {key:"Rule",value:"Rule"},
    {key:"Role",value:"Role"},
    {key:"MenuGroup",value:"Menu group"},
    {key:"User",value:"User"},
    {key:"Appearance",value:"Appearance"},
    {key:"ValueOfAppearance",value:"Value of appearance"},
    {key:"Icon",value:"Icon"},
    {key:"QuickIcon",value:"Quick Icon"},
    {key:"MenuGroup",value:"Group Menu"},
    {key:"Dashboard",value:"Dashboard"},
    {key:"Management",value:"Management"},
    {key:"LoginPage",value:"Login Page"},
    {key:"Settings",value:"Settings"},
    {key:"Youtube",value:"Youtube"},
    {key:"AdminPage",value:"Admin Page"},
    {key:"Administrator",value:"Administrator"},
    {key:"EmployeePage",value:"Employee"},
    {key:"Search",value:"Search"},
    {key:"SearchByKey",value:"Search base on keys"},
    {key:"MoreOptions",value:"More options"},
    {key:"Type",value:"Type"},
    {key:"Alert",value:"Alert"},
    {key:"Details",value:"Details"},
    {key:"DetailsInfo",value:"Details"},
    {key:"DataFilterOptions",value:"Data filter options"},
    {key:"AdvancedSearch", value: "Advanced search"},

    {key:"NewGroup",value:"New Group"},
    {key:"Features",value:"FEATURES"},
    {key:"NewMenu",value:"New Menu"},
    {key:"NewMenuGroup",value:"New Menu Group"},
    {key:"NewQuickIcon",value:"New Quick Icon"},
    {key:"NewRole",value:"New Role"},
    {key:"NewRule",value:"New Rule"},
    {key:"RegisterUser",value:"Register A Account"},
    {key:"Welcome",value:"Welcome"},
    {key:"DoccumentManagement",value:"Doccument Management"},
    {key:"RecycleBin",value:"Recycle Bin"},
    {key:"History",value:"History"},
    {key:"MenuClose",value:"Close Menu"},
    {key:"DeleteAll",value:"DeleteAll"},
    {key:"RestoreAll",value:"RestoreAll"},
    {key:"Restore",value:"Restore"},

    {key:"OrderNumber",value:"Order Number"},
    {key:"Key",value:"Key"},
    {key:"Status",value:"Status"},
    {key:"ActiveStatus",value:"Active status"},
    {key:"IsActive",value:"Is Active"},
    {key:"Active",value:"Active"},
    {key:"InActive",value:"InActive"},
    {key:"Title",value:"Title"},
    {key:"DisplayName",value:"Display name"},
    {key:"Url",value:"Url"},
    {key:"Component",value:"Component"},
    {key:"Active",value:"Active"},

    {key:"QuickReport",value:"Quick report"},

    // Card List
    {key:"NewCard",value:"New Card"},
    {key:"Name",value:"Name"},
    {key:"Code",value:"Code"},
    {key:"UpdateCard",value:"Update Card"},
    {key:"ExistCode",value:"Exist Code"},
    {key:"TaskCode",value:"Task Code"},

    // Delete Account
    {key:"DangerZone",value:"Danger Zone"},
    {key:"DangerZoneDescription",value:"Irreversible and destructive actions"},
    {key:"DeleteAccount",value:"Delete Account"},
    {key:"DeleteAccountDescription",value:"Once you delete your account, there is no going back. This will permanently delete your account, all your tenants, spaces, projects, and tasks."},
    {key:"DeleteMyAccount",value:"Delete My Account"},
    {key:"DeleteAccountConfirmMessage",value:"Are you absolutely sure? This action cannot be undone. This will permanently delete your account, all your tenants, spaces, projects, and tasks."},
    {key:"AccountDeletedSuccessfully",value:"Your account has been deleted successfully"},
    {key:"FailedToDeleteAccount",value:"Failed to delete account. Please try again."},

    // Home key
    {key:"InternalNotification",value:"Internal Notification"},
    {key:"WorkingTask",value:"Working Task"},
    {key:"MyWorking",value:"My Working"},
    {key:"MyParticipantWork",value:"My Participant Work"},
    {key:"MyObserveWork",value:"My Observe Work"},
    {key:"CreatedBy",value:"Created by"},
    {key:"SeeMore",value:"See more"},
    {key:"SeeLess",value:"See less"},

    // key cảnh báo
    {key:"NoMoreInformation",value:"No more information for {{title}}"},
    {key:"NoData",value:"No Data"},
    {key:"LoadDataFail",value:"Load data Fail!"},
    {key:"FailedAdding",value:"Create failure!"},
    {key:"SuccessAdding",value:"Create success!"},
    {key:"FailedSaving",value:"Update failed!"},
    {key:"SuccessSaving",value:"Update successful!"},
    {key:"FailedDeleting",value:"Delete failed!"},
    {key:"SuccessDeleting",value:"Successfully deleted!"},
    {key:"LoadPaginationFail",value:"Load Pagination Fail!"},
    {key:"NotEmpty",value:"Not Empty"},
    {key:"MustNotEmpty",value:"Must Not Empty"},
    {key:"ExistKey",value:"Exist Key."},
    {key:"MustMinIs1",value:"Must Min Is 1."},

    // key modal
    {key:"New",value:"New"},
    {key:"AddMore",value:"Add more"},
    {key:"Add",value:"Add"},
    {key:"UpdateMore",value:"Update More"},
    {key:"Retry",value:"Retry"},
    {key:"Close",value:"Close"},
    {key:"Delete",value:"Delete"},
    {key:"Save",value:"Save"},
    {key:"Saving",value:"Saving"},
    {key:"PreviousPage",value:"previous Page"},
    {key:"NextPage",value:"next Page"},
    {key:"Yes",value:"Yes"},
    {key:"No",value:"No"},
    {key:"Submit",value:"Submit"},
    {key:"InputKeyOfGroupGenu",value:"input key of group menu"},
    {key:"InputIconOfGroupMenu",value:"input icon of group menu"},
    // key Title
    {key:"Connection",value:"Connection"},
    {key:"InsertGroup",value:"Insert Group"},
    {key:"InsertMenu",value:"Insert Menu"},
    {key:"InsertMenuGroup",value:"Insert Group Menu"},
    {key:"MenuFilterData",value:"Menu Filter Data"},
    {key:"FilterwithActiveProperty",value:"Filter with Active Property"},
    {key:"MenuGroupData",value:"Menu Group Data"},
    {key:"MenuData",value:"Menu Data"},
    {key:"QuickIconData",value:"Quick Icon Data"},
    {key:"Description",value:"Description"},
    {key:"RoleInfomation",value:"RoleInfomation"},
    {key:"RuleInfomation",value:"RuleInfomation"},
    {key:"NewRootOrganization",value:"NewRootOrganization"},
    {key:"NewTechnique",value:"NewTechnique"},
    {key:"NewNotifyGroup",value:"NewNotifyGroup"},
    {key:"RegisterNotifyGroup",value:"RegisterNotifyGroup"},
    {key:"RoleData",value:"Role Data"},
    {key:"ConfigTable",value:"Config Table"},
    {key:"NavbarTitle",value:"DOCUMENT MANAGEMENT SYSTEM"},
    {key:"Document",value:"Document"},
    {key:"Log records",value:"Log records"},
    {key:"From Date",value:"From Date"},
    {key:"To Date",value:"To Date"},
    {key:"Actions",value:"Actions"},
    {key:"Uploaded Date",value:"Uploaded Date"},
    {key:"Last modified by",value:"Last modified by"},
    {key:"PO Number",value:"PO Number"},
    {key:"Shipper Number",value:"Shipper Number"},
    {key:"File Size",value:"File Size"},
    {key:"File size",value:"File size"},
    {key:"File",value:"File"},
    {key:"Metadata 1",value:"Metadata 1"},
    {key:"CLIENT IP",value:"CLIENT IP"},
    {key:"All",value:"All"},
    {key:"Event",value:"Event"},
    {key:"Timestamp",value:"Timestamp"},
    {key:"Client IP",value:"Client IP"},
    {key:"Title",value:"Title"},
    {key:"Upload Document",value:"Upload Document"},
    {key:"Add Document",value:"Add Document"},
    {key:"Upload & Retrieve Metadata",value:"Upload & Retrieve Metadata"},
    {key:"Metadata",value:"Metadata"},
    {key:"Display",value:"Display"},
    {key:"Add metadata",value:"Add metadata"},
    {key:"Reporting",value:"Reporting"},
    {key:"Expose API for Other System",value:"Expose API for Other System"},
    {key:"Expose API for Other System To Run OCR",value:"Expose API for Other System To Run OCR"},
    {key:"Share API for OCR Integration",value:"Share API for OCR Integration"},
    {key:"Connect API from External System",value:"Connect API from External System"},
    {key:"Generate Connection String",value:"Generate Connection String"},
    {key:"Connection String",value:"Connection String"},
    {key:"API Documentation",value:"API Documentation"},
    {key:"No connection string available. Click button to generate.",value:"No connection string available. Click button to generate."},
    {key:"No connection string available. Click to select a document type.",value:"No connection string available. Click to select a document type."},
    {key:"Request",value:"Request"},
    {key:"Response",value:"Response"},
    {key:"Example",value:"Example"},
    {key: "Response Codes", value: "Response Codes"},
    {key: "Status Code", value: "Status Code"},
    {key: "Description", value: "Description"},
    {key:"Success. Returns the exported file.", value: "Success. Returns the exported file." },
    {key:"Success. Return the OCR-run file.", value: "Success. Return the OCR-run file." },
    {key:"Request Body Schema", value: "Request Body Schema" },
    {key:"Bad Request. Invalid parameters provided.", value: "Bad Request. Invalid parameters provided." },
    {key:"Unauthorized. Invalid API key.", value: "Unauthorized. Invalid API key." },
    {key:"Forbidden. Invalid Origin header.", value: "Forbidden. Invalid Origin header." },
    {key: "Status", value: "Status"},
    {key: "Required", value: "Required"},
    {key: "Parameter", value: "Parameter"},
    {key: "Must be application/json", value: "Must be application/json"},
    {key: "Your generated API key for authentication", value: "Your generated API key for authentication"},
    {key: "The domain of your application", value: "The domain of your application"},
    {key: "Array of column configurations", value: "Array of column configurations"},
    {key: "The ID of the document to export", value: "The ID of the document to export"},
    {key: "The type of document to export", value: "The type of document to export"},
    {key: "The type of document to run OCR", value: "The type of document to run OCR"},
    {key: "List of files to select for OCR", value: "List of files to select for OCR"},
    {key: "or", value: "or"},
    {key: "Array", value: "Array"},
    {key: "String", value: "String"},
    {key: "Files", value: "Files"},
    {key: "All documentation for each shipment is to be combined into Adobe Acrobat (*.pdf) file.", value: "All documentation for each shipment is to be combined into Adobe Acrobat (*.pdf) file."},
    {key: "The packing slip number must be unique to each shipment.", value: "The packing slip number must be unique to each shipment."},
    {key: "The maximum file size of an uploaded file is 25 MB.", value: "The maximum file size of an uploaded file is 25 MB."},
    {key: "When you submit file will auto detect field that defined in template of Document Type.", value: "When you submit file will auto detect field that defined in template of Document Type."},
    {key: "NOTE", value: "NOTE"},
    {key: "To use this feature, please create a document type and set up a template rule. If these haven't been created yet", value: "To use this feature, please create a document type and set up a template rule. If these haven't been created yet"},
    {key: "click here", value: "click here"},
    {key: "to get started", value: "to get started"},
    {key: "Please upload a template", value: "Please upload a template"},
    {key: "_Document_Report", value: "Document Report"},
    {key: "No data available. Please select a text type.", value: "No data available. Please select a text type."},
    {key: "Submit Files", value: "Submit Files"},
    {key: "Export format", value: "Export format"},
    {key: "Header Parameters", value: "Header Parameters"},
    {key:"DocumentExportScope",value:"Document export scope"},
    {key:"SingleDocument",value:"Single document"},
    {key:"SelectAll",value:"Select all"},
    {key:"SelectDocument",value:"Select document"},
    {key:"All documents",value:"All documents"},
    {key:"SelectDataFields",value:"Select data fields"},
    {key:"SelectExportFormat",value:"Select export format"},
    {key:"Export",value:"Export"},
    {key:"Document Type And Scope",value:"Document type and scope"},
    {key:"ExportSettings",value:"Export settings"},
    {key:"DocumentData",value:"Document data"},

    {key:"Check this box if you want to automatically run OCR extraction on uploaded documents", value:"Check this box if you want to automatically run OCR extraction on uploaded documents" },
    {key:'No documents added yet. Click "Add Document" to begin.', value:'No documents added yet. Click "Add Document" to begin.' },
    {key: "Data Extraction", value: "Data extraction" },
    {key:'Click "Add metadata" to add new metadata', value:'Click "Add metadata" to add new metadata' },
    {key:'No fields added yet. Click "Add field" to start.', value:'No fields added yet. Click "Add field" to start.' }
];
