module.exports=[
    // key hệ thống
    {key:"Login",value:"Đăng nhập"},
    {key:"SignUp",value:"Đăng ký"},
    {key:"SignInToYourAccount",value:"Đăng nhập vào tài khoản của bạn"},
    {key:"InvalidSigninInformation",value:"Sai thông tin đăng nhập!"},
    {key:"ForgotPassword",value:"Quên mật khẩu"},
    {key:"UserName",value:"Tài khoản"},
    {key:"PassWord",value:"Mật khẩu"},
    {key:"RememberMe",value:"Ghi nhớ"},

    {"key":"DoYouWantDelete",value: "Bạn có muốn xóa {{title}} không?"},
    {"key":"DoYouWantApprove",value: "Bạn có muốn duyệt {{title}} không?"},
    { "key": "DoYouWantReject", value: "Bạn có muốn từ chối {{title}} không?" },
    {key:"DoYouWantRecall",value: "Bạn có muốn thu hồi {{title}} không?"},
    {key:"DoYouWantResetPassword",value: "Bạn có muốn reset mật khẩu cho tài khoản: {{title}}?"},
    {key:"DoYouWantThrowToRecyclebin",value: "Bạn có muốn bỏ {{title}} vào thùng rác không?"},
    {key:"DoYouWantRestoreFromRecyclebin",value: "Bạn có khôi phục {{title}} khỏi thùng rác không?"},
    {key:"DoYouWantRejectNotify",value: "Bạn có từ chối tin {{title}} không?"},
    {key:"HomePage",value:"Trang chủ"},
    {key:"Menu",value:"Menu"},
    {key:"Group",value:"Nhóm"},
    {key:"DepartmentGroup",value:"Nhóm phòng ban"},
    {key:"Rule",value:"Quyền"},
    {key:"Role",value:"Vai trò"},
    {key:"User",value:"Tài khoản"},
    {key:"MenuGroup",value:"Nhóm menu"},
    {key:"Appearance",value:"Style hiển thị"},
    {key:"ValueOfAppearance",value:"Giá trị style"},
    {key:"Icon",value:"Biểu tượng"},
    {key:"QuickIcon",value:"Tiện ích nhanh"},
    {key:"MenuGroup",value:"Nhóm menu"},
    {key:"Dashboard",value:"Tổng quan"},
    {key:"Management",value:"Quản trị"},
    {key:"LoginPage",value:"Trang đăng nhập"},
    {key:"Settings",value:"Thiết đặt"},
    {key:"Youtube",value:"Trang Youtube"},
    {key:"AdminPage",value:"Trang quản trị"},
    {key:"Administrator",value:"Người quản trị"},
    {key:"EmployeePage",value:"Trang Người dùng"},
    {key:"Search",value:"Tìm kiếm"},
    {key:"SearchByKey",value:"Tìm theo từ khóa"},
    {key:"MoreOptions",value:"Tùy chọn"},
    {key:"Type",value:"Loại"},
    {key:"Alert",value:"Cảnh báo"},
    {key:"Details",value:"Chi tiết"},
    {key:"DetailsInfo",value:"Thông tin chi tiết"},
    {key:"DataFilterOptions",value:"Tùy chọn lọc dữ liệu"},
    {key:"AdvancedSearch", value: "Tìm kiếm nâng cao"},

    {key:"NewGroup",value:"Tạo mới nhóm"},
    {key:"Features",value:"TÍNH NĂNG"},
    {key:"NewMenu",value:"Tạo mới menu"},
    {key:"NewMenuGroup",value:"Tạo mới nhóm menu"},
    {key:"NewQuickIcon",value:"Tạo mới tiện ích nhanh"},
    {key:"NewRole",value:"Tạo mới vai trò"},
    {key:"NewRule",value:"Tạo mới quyền"},
    {key:"RegisterUser",value:"Tạo mới tài khoản"},
    {key:"Welcome",value:"Xin chào"},
    {key:"DoccumentManagement",value:"Quản lý nội dung"},
    {key:"RecycleBin",value:"Thùng rác"},
    {key:"History",value:"Lịch sử"},
    {key:"MenuClose",value:"Đóng menu"},
    {key:"DeleteAll",value:"DeleteAll"},
    {key:"RestoreAll",value:"RestoreAll"},
    {key:"Restore",value:"Khôi phục"},

    {key:"OrderNumber",value:"Số thứ tự"},
    {key:"Key",value:"Từ khóa"},
    {key:"Status",value:"Trạng thái"},
    {key:"ActiveStatus",value:"Trạng thái hoạt động"},
    {key:"IsActive",value:"Kích hoạt"},
    {key:"Active",value:"Hoạt động"},
    {key:"InActive",value:"Vô hiệu hóa"},
    {key:"Title",value:"Tiêu đề"},
    {key:"DisplayName",value:"Tên hiển thị"},
    {key:"Url",value:"Đường dẫn"},
    {key:"Component",value:"Thành phần"},
    {key:"Active",value:"Kích hoạt"},

    {key:"QuickReport",value:"Báo cáo nhanh"},

    // Card List
    {key:"NewCard",value:"Tạo mới thẻ"},
    {key:"Name",value:"Tên thẻ"},
    {key:"Code",value:"Mã thẻ"},
    {key:"UpdateCard",value:"Cập nhập card"},
    {key:"ExistCode",value:"Code đã tồn tại"},
    {key:"TaskCode",value:"Mã công việc"},

    // Delete Account
    {key:"DangerZone",value:"Vùng nguy hiểm"},
    {key:"DangerZoneDescription",value:"Các hành động không thể hoàn tác và có tính phá hủy"},
    {key:"DeleteAccount",value:"Xóa tài khoản"},
    {key:"DeleteAccountDescription",value:"Khi bạn xóa tài khoản, không thể hoàn tác. Điều này sẽ xóa vĩnh viễn tài khoản, tất cả tenant, space, project và task của bạn."},
    {key:"DeleteMyAccount",value:"Xóa tài khoản của tôi"},
    {key:"DeleteAccountConfirmMessage",value:"Bạn có chắc chắn không? Hành động này không thể hoàn tác. Điều này sẽ xóa vĩnh viễn tài khoản, tất cả tenant, space, project và task của bạn."},
    {key:"AccountDeletedSuccessfully",value:"Tài khoản đã được xóa thành công"},
    {key:"FailedToDeleteAccount",value:"Không thể xóa tài khoản. Vui lòng thử lại."},

    // Home key
    {key:"InternalNotification",value:"bản tin nội bộ"},
    {key:"WorkingTask",value:"Công việc cần xử lý"},
    {key:"MyWorking",value:"Công việc của tôi"},
    {key:"MyParticipantWork",value:"Công việc tham gia"},
    {key:"MyObserveWork",value:"Công việc giám sát"},
    {key:"CreatedBy",value:"Được tạo bởi"},
    {key:"SeeMore",value:"Xem thêm"},
    {key:"SeeLess",value:"Thu gọn"},

    // key cảnh báo
    {key:"NoMoreInformation",value:"Chưa thêm thông tin nào cho {{title}}."},
    {key:"NoData",value:"Không có dữ liệu"},
    {key:"LoadDataFail",value:"Tải dữ liệu thất bại!"},
    {key:"FailedAdding",value:"Tạo mới thất bại!"},
    {key:"SuccessAdding",value:"Tạo mới thành công!"},
    {key:"FailedSaving",value:"Cập nhật thất bại!"},
    {key:"SuccessSaving",value:"Cập nhật thành công!"},
    {key:"FailedDeleting",value:"Xóa thất bại!"},
    {key:"SuccessDeleting",value:"Xóa thành công!"},
    {key:"LoadPaginationFail",value:"Tải thanh phân trang thất bại!"},
    {key:"NotEmpty",value:"Dữ liệu trống"},
    {key:"MustNotEmpty",value:"Không được để trống"},
    {key:"ExistKey",value:"Khóa tồn tại"},
    {key:"MustMinIs1",value:"Phải tối thiểu là 1."},

    // key modal
    {key:"New",value:"Thêm mới"},
    {key:"Add",value:"Thêm"},
    {key:"AddMore",value:"Tạo thêm"},
    {key:"UpdateMore",value:"Cập nhật thêm"},
    {key:"Retry",value:"Thử lại"},
    {key:"Close",value:"Đóng"},
    {key:"Delete",value:"Xóa"},
    {key:"Save",value:"Lưu"},
    {key:"Saving",value:"Đang lưu"},
    {key:"PreviousPage",value:"Trang trước"},
    {key:"NextPage",value:"Trang sau"},
    {key:"Yes",value:"Có"},
    {key:"No",value:"Không"},
    {key:"Submit",value:"Xác nhận"},

    {key:"InputKeyOfGroupGenu",value:"Nhập từ khóa nhóm menu"},
    {key:"InputIconOfGroupMenu",value:"Nhập icon của nhóm menu"},

    // key Title
    {key:"Connection",value:"Kết nối"},
    {key:"InsertGroup",value:"Thêm nhóm"},
    {key:"InsertMenu",value:"Thêm menu"},
    {key:"InsertMenuGroup",value:"Thêm nhóm menu"},
    {key:"MenuFilterData",value:"Lọc dữ liệu menu"},
    {key:"FilterwithActiveProperty",value:"Lọc với thuộc tính hoạt động"},
    {key:"MenuGroupData",value:"Dữ liệu nhóm menu"},
    {key:"MenuData",value:"Dữ liệu menu"},
    {key:"QuickIconData",value:"Dữ liệu tiện ích nhanh"},
    {key:"Description",value:"Mô tả"},
    {key:"RoleInfomation",value:"Thông tin vai trò"},
    {key:"RuleInfomation",value:"Thông tin quyền"},
    {key:"NewRootOrganization",value:"Thêm mới tổ chức"},
    {key:"NewTechnique",value:"Thêm mới chuyên môn"},
    {key:"NewNotifyGroup",value:"Thêm mới loại thông báo"},
    {key:"RegisterNotifyGroup",value:"Đăng ký loại thông báo"},
    {key:"RoleData",value:"Dữ liệu vai trò"},
    {key:"ConfigTable",value:"Chỉnh sửa bảng"},
    {key:"NavbarTitle",value:"HỆ THỐNG QUẢN LÝ TÀI LIỆU SỐ"},
    {key:"Document",value:"Tài liệu"},
    {key:"Log records",value:"Nhật kí ghi chép"},
    {key:"From Date",value:"Từ ngày"},
    {key:"To Date",value:"Đến ngày"},
    {key:"Actions",value:"Thao tác"},
    {key:"Uploaded Date",value:"Ngày tải lên"},
    {key:"Created by",value:"Người tạo"},
    {key:"Last modified by",value:"Lần cuối sửa bởi"},
    {key:"PO Number",value:"Số PO"},
    {key:"Shipper Number",value:"Số người gửi"},
    {key:"File Size",value:"Kích thước tập tin"},
    {key:"File size",value:"Kích thước tập tin"},
    {key:"Metadata 1",value:"Metadata 1"},
    {key:"File",value:"Tập tin"},
    {key:"CLIENT IP",value:"IP của khách hàng"},
    {key:"All",value:"Tất cả"},
    {key:"Event",value:"Sự kiện"},
    {key:"Timestamp",value:"Thời gian"},
    {key:"Client IP",value:"IP của khách hàng"},
    {key:"Title",value:"Tiêu đề"},
    {key:"Upload Document",value:"Tạo mới tài liệu"},
    {key:"Add Document",value:"Thêm tài liệu"},
    {key:"Upload & Retrieve Metadata",value:"Tải lên và lấy siêu dữ liệu"},
    {key:"Metadata",value:"Siêu dữ liệu"},
    {key:"Display",value:"Hiển thị"},
    {key:"Add metadata",value:"Thêm siêu dữ liệu"},
    {key:"Reporting",value:"Báo cáo"},
    {key:"Expose API for Other System",value:"Cung cấp API cho hệ thống khác"},
    {key:"Expose API for Other System To Run OCR",value:"Cung cấp API cho hệ thống khác để chạy OCR"},
    {key:"Share API for OCR Integration",value:"Chia sẻ API để tích hợp OCR"},
    {key:"Connect API from External System",value:"Kết nối API từ hệ thống bên ngoài"},
    {key:"Generate Connection String",value:"Tạo chuỗi kết nối"},
    {key:"No connection string available. Click button to generate.",value:"Không có chuỗi kết nối có sẵn. Bấm vào nút để tạo."},
    {key:"No connection string available. Click to select a document type.",value:"Không có loại dữ liệu có sẵn. Nhấp chọn loại văn bản."},
    {key:"Request Body Schema", value: "Cấu trúc yêu cầu" },
    {key:"Connection String",value:"Chuỗi kết nối"},
    {key:"API Documentation",value:"Tài liệu API"},
    {key:"Request",value:"Yêu cầu"},
    {key:"Response",value:"Phản hồi"},
    {key:"Example",value:"Ví dụ"},
    {key:"Response Codes", value: "Mã Phản Hồi" },
    {key:"Status Code", value: "Mã Trạng Thái" },
    {key:"Description", value: "Mô Tả" },
    {key:"Success. Returns the exported file.", value: "Thành công. Trả về tệp đã xuất." },
    {key:"Success. Return the OCR-run file.", value: "Thành công. Trả về tệp đã chạy OCR." },

    {key:"Bad Request. Invalid parameters provided.", value: "Yêu cầu không hợp lệ. Cung cấp tham số không hợp lệ." },
    {key:"Unauthorized. Invalid API key.", value: "Chưa Xác Thực. Khóa API không hợp lệ." },
    {key:"Forbidden. Invalid Origin header.", value: "Bị cấm. Tiêu đề Origin không hợp lệ." },
    {key:"Status", value: "Trạng Thái" },
    {key: "Required", value: "Bắt buộc"},
    {key: "Yes", value: "Có"},
    {key: "Parameter", value: "Tham số"},
    {key: "Must be application/json", value: "Phải là application/json"},
    {key: "Your generated API key for authentication", value: "Khóa API bạn tạo để xác thực"},
    {key: "The domain of your application", value: "Tên miền của bạn"},
    {key: "Array of column configurations", value: "Mảng cấu hình cột"},
    {key: "The ID of the document to export", value: "ID của tài liệu để xuất"},
    {key: "The type of document to export", value: "Loại tài liệu để xuất"},
    {key: "The type of document to run OCR", value: "Loại tài liệu để chạy OCR"},
    {key: "List of files to select for OCR", value: "Danh sách tài liệu để chạy OCR"},
    {key: "Files", value: "Tập tin"},
    {key: "Submit Files", value: "Gửi tập tin"},
    {key: "All documentation for each shipment is to be combined into Adobe Acrobat (*.pdf) file.", value: "Tất cả các tài liệu cho mỗi lô hàng phải được kết hợp vào tệp Adobe Acrobat (*.pdf)."},
    {key: "The packing slip number must be unique to each shipment.", value: "Số phiếu đóng gói phải là duy nhất cho mỗi lô hàng."},
    {key: "The maximum file size of an uploaded file is 25 MB.", value: "Kích thước tệp tối đa của tệp được tải lên là 25 MB."},
    {key: "When you submit file will auto detect field that defined in template of Document Type.", value: "Khi bạn gửi tập tin, hệ thống sẽ tự động phát hiện trường được xác định trong mẫu của Loại tài liệu."},
    {key: "NOTE", value: "GHI CHÚ"},
    {key: "To use this feature, please create a document type and set up a template rule. If these haven't been created yet", value: "Để sử dụng tính năng này, vui lòng tạo một loại tài liệu và thiết lập một quy tắc mẫu. Nếu những quy tắc này chưa được tạo"},
    {key: "click here", value: "nhấp vào đây"},
    {key: "to get started", value: "để bắt đầu"},
    {key: "Please upload a template", value: "Vui lòng tải lên một mẫu"},
    {key: "or", value: "hoặc"},
    {key: "Array", value: "Mảng"},
    {key: "String", value: "Chuỗi"},
    {key: "Header Parameters", value: "Tham số tiêu đề"},
    {key: "Export format", value: "Định dạng xuất"},
    {key:"DocumentExportScope",value:"Phạm vi xuất dữ liệu"},
    {key:"SingleDocument",value:"Tài liệu đơn"},
    {key:"SelectAll",value:"Chọn tất cả"},
    {key: "_Document_Report", value: "Báo cáo tài liệu"},
    {key: "No data available. Please select a text type.", value: "Không có dữ liệu. Vui lòng chọn loại văn bản."},
    {key:"SelectDocument",value:"Chọn tài liệu"},
    {key:"All documents",value:"Tất cả tài liệu"},
    {key:"SelectDataFields",value:"Chọn trường dữ liệu"},
    {key:"SelectExportFormat",value:"Chọn định dạng xuất"},
    {key:"Export",value:"Xuất"},
    {key:"Document Type And Scope",value:"Loại tài liệu và phạm vi"},
    {key:"ExportSettings",value:"Cài đặt xuất tệp"},
    {key:"DocumentData",value:"Dữ liệu tài liệu"},
    {key:"Check this box if you want to automatically run OCR extraction on uploaded documents", value:"Đánh dấu vào ô này nếu bạn muốn tự động chạy trích xuất OCR trên các tài liệu đã tải lên" },
    {key:'No documents added yet. Click "Add Document" to begin.', value:'Chưa có tài liệu nào được thêm vào. Nhấp vào "Thêm tài liệu" để bắt đầu.' },
    {key: "Data Extraction", value: "Trích xuất dữ liệu" },
    {key:'Click "Add metadata" to add new metadata', value:'Nhấp vào "Thêm siêu dữ liệu" để thêm siêu dữ liệu mới' },
    {key:'No fields added yet. Click "Add field" to start.', value:'Chưa có trường nào được thêm vào. Nhấp vào "Thêm trường" để bắt đầu.' }
];
