module.exports=[
    {key:"ExtendData",value:"Extend Data"},
    {key:"Value",value:"Value"},
    {key:"YourServiceIsUnregistered",value:"Your service is unregistered"},
    {key:"UserIsExists",value:"User is exists"},
    {key:"UpdateUserInformation",value:"Update user information"},
    {key:"DataIsActive",value:"Data is active"},
    {key:"Country",value:"Country"},
    {key:"Village",value:"Village"},
    {key:"ComputerSkills",value:"Computer skills"},
    {key:"EnglishLevel",value:"English level"},
    {key:"ProjectAndTask",value:"Project - task"},
    {key:"NoInformationHasBeenSelectedYet",value:"No information has been selected yet"},
    {key:"MasterDirectory",value:"Master directory"},
    {key:"Directory",value:"Directory"},
    {key:"DesignWorkflow",value:"Design workflow"},
    {key:"HumanResourceManagement",value:"Human resource management"},
    {key:"JourneyTimeForm",value:"Journey time form"},
    {key:"FindByName",value:"Find by name"},
    {key:"UpdateAccountGroupInformation",value:"Update account group information"},
    {key:"SelectedPart",value:"Selected part"},
    {key:"DoYouWantDeleteThisInformation",value:"Do you want delete this information"},
    {key:"DoYouWantRestoreThisInformation",value:"Do you want restore this information"},
    {key:"book_number",value:"Book Number"},
    {key:"from_number",value:"From number"},
    {key:"to_number",value:"To number"},
    {key:"grant_permission_for_storage",value:"Grant permission for storage"},
    {key:"InsertDepartmentGroup",value:"Insert Department Group"},
    {key:"Feature",value:"Feature"},
    {key:"FeatureName",value:"Feature name"},
    {key:"ApplyNewStorageFlow",value:"Apply new storage flow"},
    {key:"ApplyNewStorageFlowDescription",value:"When this feature is applied, the process of Outgoing Dispatch and Workflow play after storage will not be displayed"},
    {key:"FindByCode",value:"Find by code"},
    {key:"Document type",value:"Document type"},
    {key:"DocumentType",value:"Document type"},
    {key:"Year",value:"Year"},
    {key:"Going dispatch book type",value:"Going dispatch book type"},
    {key:"PersonInChargeOfLeadershipLevel",value:"Person in chare of leadership level"},
    {key:"PersonInChargeOfDepartmentLeadershipLevel",value:"Person in chare of department leadership level"},
    { key: "NotConfiguredYet", value: "Not configured yet" },
    { key: "Allow use document feature", value: "Allow use document feature" },
    { key: "Allow manage document feature", value: "Allow manage document feature" },
    { key: "Allow delete document", value: "Allow manage document" },
    { key: "Grant access view document", value: "Grant access view document" },
    { key: "Not allow view document", value: "Not allow view document" },
    { key: "Allow view document vendor of user", value: "Allow view document vendor of user" },
    { key: "Allow view document all vendor", value: "Allow view document all vendor" },
    { key: "Allow view document of specific vendor", value: "Allow view document of specific vendor" },
    { key: "User has reached maximum limit", value: "User has reached maximum limit" },
    { key: "DocumentOCR", value: "Document OCR"},
    { key: "Is the Document type tab visible", value: "Is the Document type tab visible"},
    { key: "Permission to view document OCR", value: "Permission to view document OCR"},
    { key: "Permission to manipulate the document OCR", value: "Permission to manipulate the document OCR"},
    { key: "Permission to delete the document OCR", value: "Permission to delete the document OCR"},
    { key: "Permission to use the project-task management feature", value: "Permission to use the project-task management feature" },
    { key: "Permission to delegate task assignment to superiors", value: "Permission to delegate task assignment to superiors" },
    { key: "Permission to create recurring tasks", value: "Permission to create recurring tasks" },
    { key: "All departments", value: "All departments" },
    { key: "Specific departments", value: "Specific departments" },
    { key: "Can monitor department tasks", value: "Can monitor department tasks" },
    { key: "Cannot monitor", value: "Cannot monitor" },
    { key: "Currently working", value: "Currently working" },
    { key: "Also able to edit, delete, and cancel tasks you have created before they are completed", value: "Also able to edit, delete, and cancel tasks you have created before they are completed" },
    { key: "Cannot create new tasks", value: "Cannot create new tasks" },
    { key: "Update unit task information such as title, content, status (except completed), progress, checklist, proof, comments, create subtasks, create transfer notes, create approval documents, create notifications", value: "Update unit task information such as title, content, status (except completed), progress, checklist, proof, comments, create subtasks, create transfer notes, create approval documents, create notifications" },
    { key: "Cannot edit, delete, or cancel tasks not created by you", value: "Cannot edit, delete, or cancel tasks not created by you" },
    { key: "Cannot edit, delete, or cancel tasks belonging to the department", value: "Cannot edit, delete, or cancel tasks belonging to the department" },
    { key: "Not allowed to perform", value: "Not allowed to perform" },
    { key: "Only within the unit", value: "Only within the unit" },
    { key: "Do not receive notifications for tasks/jobs not created by you", value: "Do not receive notifications for tasks/jobs not created by you" },
    { key: "This is the decision-making permission on the detailed information interface of an incoming document, displaying only the task status, or allowing to click to view detailed task information and subtasks of the task", value: "This is the decision-making permission on the detailed information interface of an incoming document, displaying only the task status, or allowing to click to view detailed task information and subtasks of the task" },
    { key: "Not allowed to view", value: "Not allowed to view" },
    { key: "Can only view incoming documents belonging to the working unit", value: "Can only view incoming documents belonging to the working unit" },
    { key: "All incoming documents", value: "All incoming documents" },
    { key: "Incoming documents belonging to specific departments", value: "Incoming documents belonging to specific departments" },
    { key: "Grant access delete document", value: "Grant access delete document"},
    { key: "Not allow delete document", value: "Not allow delete document" },
    { key: "Allow delete document vendor of user", value: "Allow delete document vendor of user" },
    { key: "Allow delete document all vendor", value: "Allow delete document all vendor" },
    { key: "Allow delete document of specific vendor", value: "Allow delete document of specific vendor" },
    { key: "RequestSupport", value: "Request support" },
    { key: "Grants permission to view encrypted data fields", value: "Grants permission to view encrypted data fields" },

];
