module.exports=[
    {key:"ExtendData",value:"Phần dữ liệu mở rộng"},
    {key:"Value",value:"Giá trị"},
    {key:"YourServiceIsUnregistered",value:"Bạn chưa đăng ký dịch vụ này"},
    {key:"UserIsExists",value:"Tài khoản đã tồn tại"},
    {key:"UpdateUserInformation",value:"Cập nhật thông tin tài khoản"},
    {key:"DataIsActive",value:"Dữ liệu đang trong trạng thái hoạt động"},
    {key:"Country",value:"Đất nước"},
    {key:"Village",value:"Thôn, làng"},
    {key:"ComputerSkills",value:"Trình độ tin học"},
    {key:"EnglishLevel",value:"Trình độ anh văn"},
    {key:"ProjectAndTask",value:"Dự án - công việc"},
    {key:"NoInformationHasBeenSelectedYet",value:"Chưa có thông tin nào được chọn"},
    {key:"MasterDirectory",value:"Danh sách danh mục"},
    {key:"Directory",value:"Danh mục"},
    {key:"DesignWorkflow",value:"Thiết kế quy trình"},
    {key:"HumanResourceManagement",value:"Quản lý nhân sự"},
    {key:"JourneyTimeForm",value:"Giấy đi đường"},
    {key:"FindByName",value:"Tìm theo tên"},
    {key:"UpdateAccountGroupInformation",value:"Cập nhật thông tin nhóm tài khoản"},
    {key:"SelectedPart",value:"Phần đã chọn"},
    {key:"DoYouWantDeleteThisInformation",value:"Bạn có muốn xoá thông tin này không"},
    {key:"DoYouWantRestoreThisInformation",value:"Bạn có muốn khôi phục thông tin này không"},
    {key:"book_number",value:"Quyển số"},
    {key:"from_number",value:"Từ số"},
    {key:"to_number",value:"Đến số"},
    {key:"grant_permission_for_storage",value:"Cấp quyền cho tính năng lưu trữ"},
    {key:"InsertDepartmentGroup",value:"Thêm mới nhóm phòng ban"},
    {key:"Feature",value:"Tính năng"},
    {key:"FeatureName",value:"Tên tính năng"},
    {key:"ApplyNewStorageFlow",value:"Áp dụng luồng lưu trữ mới"},
    {key:"ApplyNewStorageFlowDescription",value:"Khi tính năng này được áp dụng, quá trình của Công văn đi và Quy trình sau khi được lưu trữ sẽ không được hiện thị"},
    {key:"FindByCode",value:"Tìm theo mã"},
    {key:"Document type",value:"Loại văn bản"},
    {key:"Year",value:"Năm"},
    {key:"Going dispatch book type",value:"Loại số công văn đi"},
    {key:"PersonInChargeOfLeadershipLevel",value:"Người chịu trách nhiệm cấp lãnh đạo"},
    {key:"PersonInChargeOfDepartmentLeadershipLevel",value:"Người chịu trách nhiệm cấp đơn vị"},
    { key: "NotConfiguredYet", value: "Chưa cấu hình" },
    { key: "Allow use document feature", value: "Cấp quyền sử dụng tính năng tài liệu" },
    { key: "Allow manage document feature", value: "Cấp quyền quản trị tính năng tài liệu" },
    { key: "Allow delete document", value: " Cấp quyền xóa tài liệu" },
    { key: "Grant access view document", value: "Cấp quyền xem tài liệu" },
    { key: "Not allow view document", value: "Không được xem tài liệu" },
    { key: "Allow view document vendor of user", value: "Được phép xem tài liệu của nhà cung cấp của người dùng" },
    { key: "Allow view document all vendor", value: "Được phép xem tài liệu của toàn bộ nhà cung cấp" },
    { key: "Allow view document of specific vendor", value: "Được phép xem tài liệu của toàn bộ nhà cung cấp" },
    { key: "User has reached maximum limit", value: "Số người dùng đã đạt đến giới hạn tối đa" },
    { key: "DocumentOCR", value: "Tài liệu OCR"},
    { key: "Is the Document type tab visible", value: "Quyền truy cập thẻ Loại tài liệu"},
    { key: "Permission to view document OCR", value: "Quyền được truy cập tài liệu OCR"},
    { key: "Permission to manipulate the document OCR", value: "Quyền được thao tác với tài liệu OCR"},
    { key: "Permission to delete the document OCR", value: "Quyền được xóa tài liệu OCR"},
    { key: "Permission to use the project-task management feature", value: "Quyền sử dụng tính năng quản lý dự án - công việc" },
    { key: "Permission to delegate task assignment to superiors", value: "Ủy quyền phân công công việc cho cấp trên" },
    { key: "Permission to create recurring tasks", value: "Tạo công việc có tính chất lặp lại theo chu kỳ" },
    { key: "All departments", value: "Tất cả phòng ban" },
    { key: "Specific departments", value: "Một số phòng ban cụ thể" },
    { key: "Can monitor department tasks", value: "Có thể theo dõi công việc của phòng ban" },
    { key: "Cannot monitor", value: "Không được theo dõi" },
    { key: "Currently working", value: "Đang làm việc" },
    { key: "Also able to edit, delete, and cancel tasks you have created before they are completed", value: "Cũng có thể chỉnh sửa, xoá và huỷ bỏ các công việc bạn đã tạo trước khi những dữ liệu này hoàn thành" },
    { key: "Cannot create new tasks", value: "Không được tạo mới" },
    { key: "Update unit task information such as title, content, status (except completed), progress, checklist, proof, comments, create subtasks, create transfer notes, create approval documents, create notifications", value: "Cập nhật thông tin công việc đơn vị như: tiêu đề, nội dung, trạng thái ( trừ trạng thái completed), tiến độ, checklist, minh chứng, bình luận, tạo công việc con, tạo phiếu chuyển, tạo trình ký, tạo thông báo" },
    { key: "Cannot edit, delete, or cancel tasks not created by you", value: "Không được chỉnh sửa, xoá và huỷ bỏ công việc không phải do bạn tạo mới" },
    { key: "Cannot edit, delete, or cancel tasks belonging to the department", value: "Không được chỉnh hủy, xóa công việc thuộc về phòng ban" },
    { key: "Not allowed to perform", value: "Không được thực hiện" },
    { key: "Only within the unit", value: "Chỉ trong đơn vị" },
    { key: "Do not receive notifications for tasks/jobs not created by you", value: "Không nhận thông báo đầu việc/công việc không do bạn tạo mới" },
    { key: "This is the decision-making permission on the detailed information interface of an incoming document, displaying only the task status, or allowing to click to view detailed task information and subtasks of the task", value: "Đây là quyền quyết định trong giao diện thông tin chi tiết của một công văn đến, chỉ hiển thị trạng thái đầu việc thôi, hay có thể nhấn vào để xem thông tin chi tiết của đầu việc cũng như chi tiết công việc con của đầu việc" },
    { key: "Not allowed to view", value: "Không được xem" },
    { key: "Can only view incoming documents belonging to the working unit", value: "Chỉ xem được các công văn đến thuộc đơn vị đang làm việc" },
    { key: "All incoming documents", value: "Tất cả các công văn đến" },
    { key: "Incoming documents belonging to specific departments", value: "Các công văn đến thuộc một số phòng ban cụ thể" },
    { key:"Loại tài liệu", value:"Document type"},
    { key: "Grant access delete document", value: "Cấp quyền xóa tài liệu" },
    { key: "Not allow delete document", value: "Không được xem tài liệu" },
    { key: "Allow delete document vendor of user", value: "Được phép xóa tài liệu của nhà cung cấp của người dùng" },
    { key: "Allow delete document all vendor", value: "Được phép xóa tài liệu của toàn bộ nhà cung cấp" },
    { key: "Allow delete document of specific vendor", value: "Được phép xóa tài liệu của toàn bộ nhà cung cấp" },
    { key: "RequestSupport", value: "Yêu cầu hỗ trợ" },
    { key: "Grants permission to view encrypted data fields", value: "Cấp quyền xem những trường dữ liệu bị mã hóa" },
];
