module.exports =[
    {key:"Profile",value:"Profile"},
    {key:"ChangePassword",value:"Change Password"},
    {key:"Signout",value:"Signout"},
    {key:"EditAvatar",value:"Edit Avata"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Profile Photo Will Changed Automatically"},
    {key:"UploadNewPhoto",value:"Upload New Photo"},
    {key:"Update",value:"Update"},
    {key:"PersonalInfomation",value:"Personal Infomation"},
    {key:"PersonalStatistics",value:"Personal Statistics"},
    {key:"RecentNotifyReceived",value:"Recent Notify Received"},
    {key:"ViewMore",value:"View More"},
    {key:"Collapse",value:"Collapse"},
    {key:"RecentInfomations",value:"Recent Infomations"},
    {key:"MySettings",value:"My Settings"},
    {key:"Tenants",value:"Tenants"},
    {key:"ProfileDescription",value:"Your personal information and account security settings."},
    {key:"Avatar",value:"Avatar"},
    {key:"FullName",value:"Full Name"},
    {key:"Password",value:"Password"},
    {key:"User",value:"User"},
    {key:"EmailAddress",value:"Email address"},
    {key:"EmailCannotBeChanged",value:"Email cannot be changed as it has been verified"},
    {key:"EnterNewPassword",value:"Enter New Password"},
    {key:"AppearanceDescription",value:"Choose light or dark mode, or switch your mode automatically based on your system settings."},
    {key:"Light",value:"Light"},
    {key:"Dark",value:"Dark"},
    {key:"SaveChanges",value:"Save Changes"},
    {key:"ProfileUpdatedSuccessfully",value:"Profile updated successfully"},
    {key:"FailedToUpdateProfile",value:"Failed to update profile. Please try again."},
    {key:"PasswordManagedByGoogle",value:"Password managed by Google"},
    {key:"PasswordManagedByGoogleDescription",value:"Your account is signed in with Google, so you cannot change your password here."},
    {key:"AllSettings",value:"All settings"},
    {key:"People",value:"People"},
    {key:"General",value:"General"},
    {key:"Spaces",value:"Spaces"},
    {key:"LogOut",value:"Log out"},
    {key:"ProfileSettings",value:"Profile Settings"},
    {key:"MyTenants",value:"My Tenants"},
    {key:"LoadingTenants",value:"Loading tenants..."},
    {key:"FreeForever",value:"Free Forever"},
    {key:"Person",value:"person"},
    {key:"Settings",value:"Settings"},
    {key:"Leave",value:"Leave"},
    {key:"ManagePeople",value:"Manage people"},
    {key:"SearchOrInviteByEmail",value:"Search or invite by email"},
    {key:"InvitePeople",value:"Invite people"},
    {key:"AllUsers",value:"All Users"},
    {key:"Owner",value:"Owner"},
    {key:"Admin",value:"Admin"},
    {key:"Member",value:"Member"},
    {key:"Name",value:"Name"},
    {key:"Email",value:"Email"},
    {key:"Role",value:"Role"},
    {key:"Status",value:"Status"},
    {key:"LastActive",value:"Last active"},
    {key:"InvitedBy",value:"Invited by"},
    {key:"InvitedOn",value:"Invited on"},
    {key:"NoMembersFound",value:"No members found"},
    {key:"Today",value:"Today"},
    {key:"Yesterday",value:"Yesterday"},
    {key:"DaysAgo",value:"{{count}} days ago"},
    {key:"ResendInvitation",value:"Resend invitation"},
    {key:"CancelInvite",value:"Cancel invite"},
    {key:"SetAsAdmin",value:"Set as admin"},
    {key:"SetAsMember",value:"Set as member"},
    {key:"Remove",value:"Remove"},
    {key:"GeneralSettings",value:"General Settings"},
    {key:"TenantInformation",value:"Tenant Information"},
    {key:"TenantInformationDescriptionOwner",value:"Manage your tenant's general settings and information. Only the owner can modify these settings."},
    {key:"TenantInformationDescriptionViewer",value:"View your tenant's general settings and information."},
    {key:"TenantAvatar",value:"Tenant Avatar"},
    {key:"OnlyOwnerCanChangeTenantAvatar",value:"Only the owner can change the tenant avatar"},
    {key:"TenantName",value:"Tenant Name"},
    {key:"OnlyOwnerCanChangeTenantName",value:"Only the owner can change the tenant name"},
    {key:"Members",value:"Members"},
    {key:"LoadingTenantInformation",value:"Loading tenant information..."},
    {key:"NewSpace",value:"New Space"},
    {key:"LoadingSpaces",value:"Loading spaces..."},
    {key:"NoSpacesFound",value:"No spaces found"},
    {key:"NoSpacesYet",value:"No spaces yet"},
    {key:"Space",value:"SPACE"},
    {key:"Visibility",value:"VISIBILITY"},
    {key:"SharedWith",value:"SHARED WITH"},
    {key:"GoToSpace",value:"Go to Space"},
    {key:"Private",value:"Private"},
    {key:"Public",value:"Public"},
    {key:"OnlyInvitedMembers",value:"Only invited members"},
    {key:"Everyone",value:"Everyone"},
    {key:"Share",value:"Share"},
    {key:"MakePrivate",value:"Make private"},
    {key:"ThisSectionComingSoon",value:"This section is coming soon."},
    {key:"RemoveMember",value:"Remove Member"},
    {key:"RemoveMemberConfirmMessage",value:"Are you sure you want to remove {{name}} from this workspace? This action cannot be undone."},
    {key:"ThisMember",value:"this member"},
    {key:"Cancel",value:"Cancel"},
    {key:"Saving",value:"Saving..."},
    {key:"InvitationResentSuccessfully",value:"Invitation resent successfully"},
    {key:"ResendFailed",value:"Resend failed"},
    {key:"CanceledInvite",value:"Canceled invite"},
    {key:"CancelFailed",value:"Cancel failed"},
    {key:"TenantIdMissing",value:"Tenant ID is missing"},
    {key:"MemberUsernameMissing",value:"Member username is missing"},
    {key:"ServiceMethodNotAvailable",value:"Service method not available. Please refresh the page."},
    {key:"MemberRoleUpdatedToAdmin",value:"Member role updated to admin"},
    {key:"MemberRoleUpdatedToMember",value:"Member role updated to member"},
    {key:"FailedToSetAsAdmin",value:"Failed to set as admin. Please try again."},
    {key:"FailedToSetAsMember",value:"Failed to set as member. Please try again."},
    {key:"AvatarUploadComingSoon",value:"Avatar upload coming soon"},
    {key:"TenantUpdatedSuccessfully",value:"Tenant updated successfully"},
    {key:"FailedToUpdateTenant",value:"Failed to update tenant"},
    {key:"MemberRemovedSuccessfully",value:"Member removed successfully"},
    {key:"FailedToRemoveMember",value:"Failed to remove member"},
    {key:"FailedToLoadSpaces",value:"Failed to load spaces"},
    {key:"FailedToLoadWorkspaces",value:"Failed to load workspaces"},
    {key:"FailedToLoadMembers",value:"Failed to load members"},
    {key:"AvatarUploadedSuccessfully",value:"Avatar uploaded successfully"},
    {key:"FailedToUploadAvatar",value:"Failed to upload avatar"}
];