module.exports =[
    {key:"Profile",value:"Thông tin của tôi"},
    {key:"ChangePassword",value:"Đổi mật khẩu"},
    {key:"Signout",value:"Đăng xuất"},
    {key:"EditAvatar",value:"Thay Avatar"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Ảnh đại diện sẽ tự động thay đổi"},
    {key:"UploadNewPhoto",value:"Tải ảnh mới"},
    {key:"Update",value:"Cập nhật"},
    {key:"PersonalInfomation",value:"Hồ sơ của tôi"},
    {key:"PersonalStatistics",value:"Thống kê cá nhân"},
    {key:"RecentNotifyReceived",value:"Nhận thông tin gần đây"},
    {key:"ViewMore",value:"Xem thêm"},
    {key:"Collapse",value:"Thu Gọn"},
    {key:"RecentInfomations",value:"Thông tin gần đây"},
    {key:"MySettings",value:"Cài đặt của tôi"},
    {key:"Tenants",value:"Tenants"},
    {key:"ProfileDescription",value:"Thông tin cá nhân và cài đặt bảo mật tài khoản của bạn."},
    {key:"Avatar",value:"Ảnh đại diện"},
    {key:"FullName",value:"Họ và tên"},
    {key:"Password",value:"Mật khẩu"},
    {key:"User",value:"Người dùng"},
    {key:"EmailAddress",value:"Địa chỉ email"},
    {key:"EmailCannotBeChanged",value:"Email không thể thay đổi vì đã được xác minh"},
    {key:"EnterNewPassword",value:"Nhập mật khẩu mới"},
    {key:"AppearanceDescription",value:"Chọn chế độ sáng hoặc tối, hoặc tự động chuyển đổi dựa trên cài đặt hệ thống của bạn."},
    {key:"Light",value:"Sáng"},
    {key:"Dark",value:"Tối"},
    {key:"SaveChanges",value:"Lưu thay đổi"},
    {key:"ProfileUpdatedSuccessfully",value:"Cập nhật hồ sơ thành công"},
    {key:"FailedToUpdateProfile",value:"Không thể cập nhật hồ sơ. Vui lòng thử lại."},
    {key:"PasswordManagedByGoogle",value:"Mật khẩu được quản lý bởi Google"},
    {key:"PasswordManagedByGoogleDescription",value:"Tài khoản của bạn được đăng nhập bằng Google, vì vậy bạn không thể đổi mật khẩu tại đây."},
    {key:"AllSettings",value:"Tất cả cài đặt"},
    {key:"People",value:"Người dùng"},
    {key:"General",value:"Chung"},
    {key:"Spaces",value:"Không gian"},
    {key:"LogOut",value:"Đăng xuất"},
    {key:"ProfileSettings",value:"Cài đặt hồ sơ"},
    {key:"MyTenants",value:"Tenants của tôi"},
    {key:"LoadingTenants",value:"Đang tải tenants..."},
    {key:"FreeForever",value:"Miễn phí mãi mãi"},
    {key:"Person",value:"người"},
    {key:"Settings",value:"Cài đặt"},
    {key:"Leave",value:"Rời khỏi"},
    {key:"ManagePeople",value:"Quản lý người dùng"},
    {key:"SearchOrInviteByEmail",value:"Tìm kiếm hoặc mời bằng email"},
    {key:"InvitePeople",value:"Mời người dùng"},
    {key:"AllUsers",value:"Tất cả người dùng"},
    {key:"Owner",value:"Chủ sở hữu"},
    {key:"Admin",value:"Quản trị viên"},
    {key:"Member",value:"Thành viên"},
    {key:"Name",value:"Tên"},
    {key:"Email",value:"Email"},
    {key:"Role",value:"Vai trò"},
    {key:"Status",value:"Trạng thái"},
    {key:"LastActive",value:"Hoạt động lần cuối"},
    {key:"InvitedBy",value:"Được mời bởi"},
    {key:"InvitedOn",value:"Được mời vào"},
    {key:"NoMembersFound",value:"Không tìm thấy thành viên"},
    {key:"Today",value:"Hôm nay"},
    {key:"Yesterday",value:"Hôm qua"},
    {key:"DaysAgo",value:"{{count}} ngày trước"},
    {key:"ResendInvitation",value:"Gửi lại lời mời"},
    {key:"CancelInvite",value:"Hủy lời mời"},
    {key:"SetAsAdmin",value:"Đặt làm quản trị viên"},
    {key:"SetAsMember",value:"Đặt làm thành viên"},
    {key:"Remove",value:"Xóa"},
    {key:"GeneralSettings",value:"Cài đặt chung"},
    {key:"TenantInformation",value:"Thông tin Tenant"},
    {key:"TenantInformationDescriptionOwner",value:"Quản lý cài đặt chung và thông tin của tenant. Chỉ chủ sở hữu mới có thể chỉnh sửa các cài đặt này."},
    {key:"TenantInformationDescriptionViewer",value:"Xem cài đặt chung và thông tin của tenant."},
    {key:"TenantAvatar",value:"Ảnh đại diện Tenant"},
    {key:"OnlyOwnerCanChangeTenantAvatar",value:"Chỉ chủ sở hữu mới có thể thay đổi ảnh đại diện tenant"},
    {key:"TenantName",value:"Tên Tenant"},
    {key:"OnlyOwnerCanChangeTenantName",value:"Chỉ chủ sở hữu mới có thể thay đổi tên tenant"},
    {key:"Members",value:"Thành viên"},
    {key:"LoadingTenantInformation",value:"Đang tải thông tin tenant..."},
    {key:"NewSpace",value:"Không gian mới"},
    {key:"LoadingSpaces",value:"Đang tải không gian..."},
    {key:"NoSpacesFound",value:"Không tìm thấy không gian"},
    {key:"NoSpacesYet",value:"Chưa có không gian nào"},
    {key:"Space",value:"Không gian"},
    {key:"Visibility",value:"Hiển thị"},
    {key:"SharedWith",value:"Chia sẻ với"},
    {key:"GoToSpace",value:"Đi đến không gian"},
    {key:"Private",value:"Riêng tư"},
    {key:"Public",value:"Công khai"},
    {key:"OnlyInvitedMembers",value:"Chỉ thành viên được mời"},
    {key:"Everyone",value:"Mọi người"},
    {key:"Share",value:"Chia sẻ"},
    {key:"MakePrivate",value:"Đặt riêng tư"},
    {key:"ThisSectionComingSoon",value:"Phần này sắp ra mắt."},
    {key:"RemoveMember",value:"Xóa thành viên"},
    {key:"RemoveMemberConfirmMessage",value:"Bạn có chắc chắn muốn xóa {{name}} khỏi workspace này không? Hành động này không thể hoàn tác."},
    {key:"ThisMember",value:"thành viên này"},
    {key:"Cancel",value:"Hủy"},
    {key:"Saving",value:"Đang lưu..."},
    {key:"InvitationResentSuccessfully",value:"Gửi lại lời mời thành công"},
    {key:"ResendFailed",value:"Gửi lại thất bại"},
    {key:"CanceledInvite",value:"Đã hủy lời mời"},
    {key:"CancelFailed",value:"Hủy thất bại"},
    {key:"TenantIdMissing",value:"Thiếu ID Tenant"},
    {key:"MemberUsernameMissing",value:"Thiếu tên người dùng thành viên"},
    {key:"ServiceMethodNotAvailable",value:"Phương thức dịch vụ không khả dụng. Vui lòng làm mới trang."},
    {key:"MemberRoleUpdatedToAdmin",value:"Vai trò thành viên đã được cập nhật thành quản trị viên"},
    {key:"MemberRoleUpdatedToMember",value:"Vai trò thành viên đã được cập nhật thành thành viên"},
    {key:"FailedToSetAsAdmin",value:"Không thể đặt làm quản trị viên. Vui lòng thử lại."},
    {key:"FailedToSetAsMember",value:"Không thể đặt làm thành viên. Vui lòng thử lại."},
    {key:"AvatarUploadComingSoon",value:"Tải ảnh đại diện sắp ra mắt"},
    {key:"TenantUpdatedSuccessfully",value:"Cập nhật tenant thành công"},
    {key:"FailedToUpdateTenant",value:"Không thể cập nhật tenant"},
    {key:"MemberRemovedSuccessfully",value:"Xóa thành viên thành công"},
    {key:"FailedToRemoveMember",value:"Không thể xóa thành viên"},
    {key:"FailedToLoadSpaces",value:"Không thể tải không gian"},
    {key:"FailedToLoadWorkspaces",value:"Không thể tải workspaces"},
    {key:"FailedToLoadMembers",value:"Không thể tải thành viên"},
    {key:"AvatarUploadedSuccessfully",value:"Tải ảnh đại diện thành công"},
    {key:"FailedToUploadAvatar",value:"Không thể tải ảnh đại diện"}
];